gText_ApprenticeChallenge0::
	.string "Mm, soy el aprendiz n.º {STR_VAR_2} de {STR_VAR_1}.\n"
	.string "Snif… Esta tensión puede conmigo…$"

gText_ApprenticeChallenge1::
	.string "¡Soy el aprendiz n.º {STR_VAR_2} de {STR_VAR_1}!\n"
	.string "¡Allá voy!$"

gText_ApprenticeChallenge2::
	.string "¡Soy el aprendiz n.º {STR_VAR_2} de {STR_VAR_1}!\n"
	.string "¡Acepta mi reto!$"

gText_ApprenticeChallenge3::
	.string "Mm, soy la aprendiz n.º {STR_VAR_2} de {STR_VAR_1}…\n"
	.string "¿Crees que tengo alguna posibilidad?$"

gText_ApprenticeChallenge4::
	.string "¡Soy la aprendiz n.º {STR_VAR_2} de {STR_VAR_1}!\n"
	.string "¡A ver quién es mejor!$"

gText_ApprenticeChallenge5::
	.string "Estoy muy ocupado, pero, en fin,\n"
	.string "¡soy el aprendiz n.º {STR_VAR_2} de {STR_VAR_1}!$"

gText_ApprenticeChallenge6::
	.string "¡Soy la aprendiz n.º {STR_VAR_2} de {STR_VAR_1}!\n"
	.string "¡Encantada de conocerte!$"

gText_ApprenticeChallenge7::
	.string "¡Soy la aprendiz n.º {STR_VAR_2} de {STR_VAR_1}!\n"
	.string "¿Qué? ¿Empezamos ya?$"

gText_ApprenticeChallenge8::
	.string "¡Eh! ¡Soy la aprendiz n.º {STR_VAR_2} de {STR_VAR_1}!\n"
	.string "¡Haré lo que pueda!$"

gText_ApprenticeChallenge9::
	.string "¡Eh! ¡Soy el aprendiz n.º {STR_VAR_2} de {STR_VAR_1}!\n"
	.string "¡Saca músculo!$"

gText_ApprenticeChallenge10::
	.string "¡Soy el aprendiz n.º 1.000 de {STR_VAR_1}!\n"
	.string "¡Bueno, el n.º {STR_VAR_2}! ¿Qué importa eso?$"

gText_ApprenticeChallenge11::
	.string "¡Sí, soy el aprendiz n.º {STR_VAR_2} de {STR_VAR_1}!\n"
	.string "¡Al abordaje!$"

gText_ApprenticeChallenge12::
	.string "¡Soy el aprendiz n.º {STR_VAR_2} de {STR_VAR_1}!\n"
	.string "¡Que suene la música!$"

gText_ApprenticeChallenge13::
	.string "¡Soy el aprendiz n.º {STR_VAR_2} de {STR_VAR_1}!\n"
	.string "¡Es un placer conocerte! ¡Kiaaa!$"

gText_ApprenticeChallenge14::
	.string "¡Soy el aprendiz n.º {STR_VAR_2} de {STR_VAR_1}!\n"
	.string "¡Quiero convertirme en leyenda!$"

gText_ApprenticeChallenge15::
	.string "Soy el aprendiz n.º {STR_VAR_2} de {STR_VAR_1}\n"
	.string "y yo no miento.$"

gText_ApprenticePleaseTeach0::
	.string "¿Eres… {PLAYER}?\n"
	.string "¡Oh! Snif… Snif…\p"
	.string "¡Ay! Lo-lo siento…\n"
	.string "Los nervios… No puedo dejar\l"
	.string "de llorar…\p"
	.string "So-soy {STR_VAR_1}, y tú, {PLAYER},\n"
	.string "siempre has sido mi ídolo.\p"
	.string "Yo-yo… soñaba con que algún día me\n"
	.string "pudieses enseñar cosas de los POKéMON.\p"
	.string "¡Anda, por favor, {PLAYER}!\n"
	.string "¡Enséñame algo sobre los POKéMON!$"

gText_ApprenticeRejectTeaching0::
	.string "Oh… Pe-pero…\n"
	.string "Snif… ¡Buaaaaaaaa!\p"
	.string "¡Po-po-por fa-fa-vor!\n"
	.string "¡Te lo pido po-po-por fa-fa-vor!$"

gText_ApprenticeWhichLevelMode0::
	.string "¿En serio? ¿Lo harás?\n"
	.string "¡Genial! ¡Alucinante! ¡Superguay!\p"
	.string "Oh… Perdona otra vez…\n"
	.string "Ahora lloro de alegría…\p"
	.string "Mm… Entonces, dime algo…\n"
	.string "sobre la TORRE BATALLA…\p"
	.string "¿Qué nivel crees que me iría mejor?\n"
	.string "¿El nivel 50 o el nivel libre?$"

gText_ApprenticeLevelModeThanks0::
	.string "¿{STR_VAR_1}?\n"
	.string "¡Buaaaaaa!\p"
	.string "¡Oh! ¡Lo siento otra vez!\n"
	.string "Eso de que elijas por mí me hace\l"
	.string "tan feliz que no puedo contenerme…\p"
	.string "Snif…\n"
	.string "¡Muchas gracias!\l"
	.string "¡No te olvides de mí!$"

gText_ApprenticePleaseTeach1::
	.string "¡Guau! Tú eres {PLAYER}, ¿a que sí?\n"
	.string "Guau, todo el mundo te conoce.\p"
	.string "¡Me llamo {STR_VAR_1}!\n"
	.string "¡Acabo de convertirme en ENTRENADOR!\p"
	.string "¡Porfa, {PLAYER}!\n"
	.string "¿Querrías tomarme como aprendiz para\l"
	.string "enseñarme a ser un buen ENTRENADOR?$"

gText_ApprenticeRejectTeaching1::
	.string "Ooohh, pero ¿por qué?\n"
	.string "¡Anda, porfa! ¡No seas así!\l"
	.string "¡Déjame ser tu aprendiz!$"

gText_ApprenticeWhichLevelMode1::
	.string "¡Yupi! ¡Genial!\p"
	.string "¡Lo primero que quiero preguntarte\n"
	.string "es sobre la TORRE BATALLA!\p"
	.string "Entre el nivel 50 y el nivel libre…\n"
	.string "¿En cuál crees que debería inscribirme?$"

gText_ApprenticeLevelModeThanks1::
	.string "¿{STR_VAR_1}? ¡Claro, es verdad!\n"
	.string "¡Haré lo que pueda para no defraudarte!\p"
	.string "¡Ojalá nos volvamos a ver\n"
	.string "para que me enseñes algo más!$"

gText_ApprenticePleaseTeach2::
	.string "Mm… ¿Eres {PLAYER}?\n"
	.string "Yo me llamo {STR_VAR_1}.\p"
	.string "Quiero ser un gran ENTRENADOR POKéMON,\n"
	.string "aunque no sé por dónde empezar…\p"
	.string "Ya que estás aquí, a lo mejor podrías\n"
	.string "ayudarme, con toda esa fama que tienes.\p"
	.string "¿Qué me dices, {PLAYER}? ¿Me ayudarías?$"

gText_ApprenticeRejectTeaching2::
	.string "Oh, pero…\p"
	.string "¡Pero es que de verdad que quiero\n"
	.string "ser un buen ENTRENADOR POKéMON!\p"
	.string "¡Por favor, dime que sí!$"

gText_ApprenticeWhichLevelMode2::
	.string "¡Gracias!\n"
	.string "¡Ahí va entonces mi primera pregunta!\p"
	.string "La TORRE BATALLA tiene dos niveles:\n"
	.string "el nivel 50 y el nivel libre, ¿sí?\p"
	.string "¿En cuál de los dos niveles crees\n"
	.string "que me vendría mejor participar?$"

gText_ApprenticeLevelModeThanks2::
	.string "Oh, ¿en el {STR_VAR_1}?\n"
	.string "¡Entendido!\p"
	.string "Si tengo más dudas, ¡vendré\n"
	.string "otra vez a preguntarte!$"

gText_ApprenticePleaseTeach3::
	.string "¡Oh! ¡Pero si tú eres…!\n"
	.string "No, no puede ser verdad.\p"
	.string "Yo no tengo tanta suerte como para\n"
	.string "encontrarme de repente con {PLAYER}.\p"
	.string "Pero ¿eres de verdad {PLAYER}?\n"
	.string "¡No me creo que esté hablando contigo!\p"
	.string "¡Huy, qué miedo! Siempre que me pasa\n"
	.string "algo bueno, luego viene una desgracia,\l"
	.string "y las desgracias nunca vienen solas…\p"
	.string "Perdona…\n"
	.string "Me llamo… {STR_VAR_1}…\p"
	.string "Verás, es que yo no me siento\n"
	.string "especialmente orgullosa de nada…\p"
	.string "Ni siquiera debería decir nada de mí,\n"
	.string "porque de todas maneras me olvidarás…\p"
	.string "Siempre tenía un sueño en el que\n"
	.string "te conocía, {PLAYER}, y me dabas\l"
	.string "muchos consejos sobre cómo entrenar.\p"
	.string "Pero era un sueño, ya sé que no quieres\n"
	.string "perder el tiempo con alguien como yo…\p"
	.string "¿O sí querrías darme consejos?$"

gText_ApprenticeRejectTeaching3::
	.string "Lo sabía…\p"
	.string "Era lo normal porque yo soy\n"
	.string "una don nadie…\p"
	.string "Pero, por un momento pensé…\n"
	.string "No cambiarías de opinión, ¿verdad?\p"
	.string "¡Perdona que insista, pero una ocasión\n"
	.string "así no se presenta todos los días!\p"
	.string "Por favor, ¿serías tan amable de darme\n"
	.string "unos consejillos sobre los POKéMON?$"

gText_ApprenticeWhichLevelMode3::
	.string "¿De verdad? ¡No me lo puedo creer!\n"
	.string "¡No me creo que quieras darme consejos!\l"
	.string "¡Estoy…! ¡Estoy tan contenta!…\p"
	.string "Lo primero que querría preguntarte es\n"
	.string "una tontería, pero yo no me decido…\p"
	.string "En la TORRE BATALLA, te dejan elegir\n"
	.string "entre el nivel 50 y el nivel libre.\p"
	.string "¿En cuál crees que tendría más\n"
	.string "posibilidades de ganar algo?$"

gText_ApprenticeLevelModeThanks3::
	.string "¿{STR_VAR_1}? ¡Vale!\n"
	.string "Pero ¿de verdad crees que alguien\l"
	.string "como yo tiene la menor posibilidad?\p"
	.string "Bueno, haré lo que pueda,\n"
	.string "aunque sé que no puedo mucho.\p"
	.string "¡Y perdona que te haya robado\n"
	.string "tanto tiempo!$"

gText_ApprenticePleaseTeach4::
	.string "¡Oh! Tú eres {PLAYER}, ¿verdad?\p"
	.string "¡Dicen que hay pocos ENTRENADORES\n"
	.string "que entrenen POKéMON como tú!\p"
	.string "¡Me llamo {STR_VAR_1}!\n"
	.string "¡Voy a ser tu amiga!\p"
	.string "¿Sabes?\p"
	.string "No se puede ganar nada en el FRENTE de\n"
	.string "BATALLA sabiendo únicamente lo que te\l"
	.string "enseñan en la ESCUELA de ENTRENADORES.\p"
	.string "Por eso me gustaría oír tus consejos.\n"
	.string "Si quieres dármelos, claro…$"

gText_ApprenticeRejectTeaching4::
	.string "¿Eh? ¿Por qué te niegas?\n"
	.string "¡Soy yo quien te lo está pidiendo!\l"
	.string "¡Anda, piénsatelo otra vez!$"

gText_ApprenticeWhichLevelMode4::
	.string "¡Vale, entonces, cuando tenga alguna\n"
	.string "duda, te dejo decidir por mí!\p"
	.string "Sabes que en la TORRE BATALLA está\n"
	.string "el nivel 50 y el nivel libre, ¿verdad?\p"
	.string "¿Cuál crees que es el más adecuado\n"
	.string "para mí, {PLAYER}{KUN}?$"

gText_ApprenticeLevelModeThanks4::
	.string "¿Piensas que el {STR_VAR_1}?\n"
	.string "¡Gracias!\p"
	.string "Sabiendo que lo decidiste tú, {PLAYER}{KUN},\n"
	.string "no podré enfadarme si pierdo.\p"
	.string "Bueno, ya te pediré otro consejo\n"
	.string "otro día. ¡Chao!$"

gText_ApprenticePleaseTeach5::
	.string "¡Oh, hola, {PLAYER}{KUN}!\n"
	.string "¡Todo el mundo sabe tu nombre!\l"
	.string "¡A mí llámame {STR_VAR_1}! ¡Encantado!\p"
	.string "Soy un TRIATLETA, así que me entreno\n"
	.string "a mí mismo a la vez que entreno POKéMON.\p"
	.string "También me gusta hacer otras cosas,\n"
	.string "como trabajar, hacer parapente, bailar…\p"
	.string "Comprenderás que, estando tan ocupado,\n"
	.string "no es fácil ser un buen ENTRENADOR.\p"
	.string "Pero estoy pensando…\n"
	.string "Tiene que haber un motivo para que tú\l"
	.string "y yo nos hayamos encontrado aquí.\p"
	.string "Oye, {PLAYER}{KUN}, ¿qué tal si me ayudas\n"
	.string "dándome un consejo de vez en cuando?$"

gText_ApprenticeRejectTeaching5::
	.string "Oh, pero, ¡por favor!\n"
	.string "¡Un tipo como yo necesita alguien como\l"
	.string "tú a su lado, {PLAYER}{KUN}!\p"
	.string "¡En serio, necesito tus consejos!$"

gText_ApprenticeWhichLevelMode5::
	.string "¡Gracias! ¡Eso es genial!\n"
	.string "¡Vamos a empezar por uno fácil!\p"
	.string "Ya sabes que en la TORRE BATALLA\n"
	.string "hay dos niveles de combates, ¿verdad?\l"
	.string "Ya sabes, el nivel 50 y el nivel libre.\p"
	.string "¿Cuál es el que más le conviene\n"
	.string "a un tipo tan ocupado como yo?$"

gText_ApprenticeLevelModeThanks5::
	.string "¿{STR_VAR_1}? Vale, comprendido.\n"
	.string "¡A ver cuándo tengo tiempo y pruebo!\p"
	.string "¡Huy, me tengo que largar!\n"
	.string "¡Gracias! ¡Nos vemos!$"

gText_ApprenticePleaseTeach6::
	.string "¡No puedo creerlo! ¡Eh!\n"
	.string "¿Eres tú de verdad, {PLAYER}?\p"
	.string "¡Guau! ¡Alucinante! ¡Soy {STR_VAR_1},\n"
	.string "encantada de conocerte!\p"
	.string "{PLAYER}, eres muy fuerte,\n"
	.string "¿a que sí?\p"
	.string "¡Todo el mundo habla de ti!\p"
	.string "¡Oh! ¡Tengo una idea!\n"
	.string "¡Te pediré que me aconsejes, {PLAYER}!\l"
	.string "¡Así yo también me haré más fuerte!\p"
	.string "¿A que es buena idea?\n"
	.string "¡Por favor, necesito que me aconsejes!$"

gText_ApprenticeRejectTeaching6::
	.string "Ja, ja, ja, ja. ¡A mí no me engañas!\n"
	.string "¡No puedes ser tan egoísta!\l"
	.string "En realidad, me vas a ayudar, ¿verdad?$"

gText_ApprenticeWhichLevelMode6::
	.string "¡Yupi! ¡Sabía que tenías buen corazón,\n"
	.string "{PLAYER}!\p"
	.string "¿Qué puedo preguntarte primero?…\n"
	.string "¡Ah, sí, ya sé!\p"
	.string "Y la pregunta es…\n"
	.string "Tachán, tachán…\p"
	.string "Para participar en un desafío de la\n"
	.string "TORRE BATALLA, ¿qué nivel elijo?\p"
	.string "¿El nivel 50 o el nivel libre?\n"
	.string "¿Qué sería mejor para mí?$"

gText_ApprenticeLevelModeThanks6::
	.string "¡Oh-oh-oh!\n"
	.string "¡Has dicho {STR_VAR_1}!\l"
	.string "¡Muchas gracias por tu respuesta!\p"
	.string "Creo que eso es todo lo\n"
	.string "que quería preguntarte.\p"
	.string "Nos vemos aquí otra vez, ¿vale?\n"
	.string "¡Gracias!$"

gText_ApprenticePleaseTeach7::
	.string "Ay, discúlpame, pero…\n"
	.string "¿tú no eres {PLAYER}?\p"
	.string "Me llamo {STR_VAR_1}, y para mí es\n"
	.string "todo un placer conocerte.\p"
	.string "He sido una admiradora tuya desde\n"
	.string "siempre…\p"
	.string "…\p"
	.string "Mm… Espero que me permitas\n"
	.string "el atrevimiento…\p"
	.string "¿Podría ser tu aprendiz, {PLAYER}?$"

gText_ApprenticeRejectTeaching7::
	.string "¡Oh!…\p"
	.string "¡Vaya!…\p"
	.string "Esto…\p"
	.string "Me he quedado un poco traspuesta.\n"
	.string "Perdona, he debido de oírte mal.\p"
	.string "Me vas a tomar de aprendiz, ¿verdad?$"

gText_ApprenticeWhichLevelMode7::
	.string "¡Oh!… ¡Estoy feliz!\p"
	.string "No quiero hacerte perder más tiempo,\n"
	.string "así que contéstame a esto, porfa.\p"
	.string "Tengo la intención de participar pronto\n"
	.string "en la TORRE BATALLA.\p"
	.string "Pero hay dos niveles…\p"
	.string "¿Cuál crees que se adapta mejor a mí?\n"
	.string "¿El nivel 50 o el nivel libre?$"

gText_ApprenticeLevelModeThanks7::
	.string "¿Me has dicho el {STR_VAR_1}?\n"
	.string "¡Vale! ¡A ver qué tal se me da!\p"
	.string "Oye, que muchísimas gracias, {PLAYER}.\n"
	.string "Espero que me sigas ayudando.\l"
	.string "Te me cuidas muchísimo, ¿vale?$"

gText_ApprenticePleaseTeach8::
	.string "¡No! ¡No puede ser! ¿{PLAYER}?\n"
	.string "¿De verdad eres tú?\l"
	.string "¡Qu-qué alegría!\p"
	.string "¡Yo! ¡Me llamo {STR_VAR_1}!\n"
	.string "¡Acabo de conseguir el título!\l"
	.string "¡Ya puedo entrenar POKéMON!\p"
	.string "¡Es un placer conocerte, {PLAYER}!\n"
	.string "¡Tu nombre ya es una leyenda!\p"
	.string "¡Oh-oh-oh, ya sé!\n"
	.string "¿Me dejas pedirte un enorme favor?\p"
	.string "¡Me dejarías ser tu aprendiz!\n"
	.string "¡Quiero aprender de ti!$"

gText_ApprenticeRejectTeaching8::
	.string "¡Oh, {PLAYER}!\n"
	.string "¿Me vas a rechazar?…\l"
	.string "¡Es… una oportunidad única!\p"
	.string "Perdona, pero tengo que insistir.\n"
	.string "¡{PLAYER}, por favor! ¡Dime que sí!\p"
	.string "¡Te suplico que me dejes\n"
	.string "ser tu aprendiz!$"

gText_ApprenticeWhichLevelMode8::
	.string "¡Yupi! ¡{PLAYER} ha dicho que sí!\n"
	.string "¡{PLAYER} ha dicho que sí!\p"
	.string "Ya no voy a dormir esta noche…\n"
	.string "¡Muchisísimas gracias!\p"
	.string "¡Oye, tengo una primera pregunta!\p"
	.string "En la TORRE BATALLA, qué crees que me\n"
	.string "conviene, ¿el nivel 50 o el nivel libre?$"

gText_ApprenticeLevelModeThanks8::
	.string "¡{STR_VAR_1}! ¡Vale, entiendo!\n"
	.string "¡Lo entiendo perfectamente!\l"
	.string "¡Qué genial! ¡Qué suerte!\p"
	.string "Espero que no te olvides de\n"
	.string "seguir enseñándome cosas, ¿eh?$"

gText_ApprenticePleaseTeach9::
	.string "¡Guau! ¿No serás tú…\n"
	.string "¡¿Es posible que seas… {PLAYER}{KUN}?!\l"
	.string "That strong and famous TRAINER?\l"
	.string "¡Ésta sí que es buena!\p"
	.string "¡Hola, me llamo {STR_VAR_1}!\p"
	.string "Llevo tiempo buscando un buen\n"
	.string "profesor que sepa de POKéMON.\p"
	.string "¡Y ahora llegas tú {PLAYER}{KUN},\n"
	.string "como agua de mayo!\p"
	.string "Bueno, ya lo sabes, {PLAYER}{KUN}.\n"
	.string "¿Me aceptas como tu aprendiz?$"

gText_ApprenticeRejectTeaching9::
	.string "¡Buaaaa!\n"
	.string "¡No hay nadie como tú!…\p"
	.string "No seas así, te lo pido por favor.\n"
	.string "¡Déjame ser tu aprendiz!$"

gText_ApprenticeWhichLevelMode9::
	.string "¡Genial! ¡Eso es una respuesta!\n"
	.string "¡Una excelente, si puedo decirlo!\p"
	.string "¿Por qué no me das tu primer consejo\n"
	.string "sobre la TORRE BATALLA?\p"
	.string "Si fuese a participar en un desafío,\n"
	.string "¿qué elijo, el nivel 50 o el libre?$"

gText_ApprenticeLevelModeThanks9::
	.string "¡{STR_VAR_1}!\n"
	.string "¡G-e-n-i-a-l!\l"
	.string "¡Haré exactamente lo que dices!\p"
	.string "¡Ahora que soy tu aprendiz, nos veremos\n"
	.string "más a menudo! ¡Adiós!$"

gText_ApprenticePleaseTeach10::
	.string "Eh, tú eres {PLAYER}{KUN}, ¿verdad?\n"
	.string "¡Te está buscando la policía!\p"
	.string "…\n"
	.string "¡Es broma!\p"
	.string "Yo me llamo {STR_VAR_1}. Aunque no lo\n"
	.string "parezca, soy un CAMPEÓN POKéMON…\l"
	.string "¡Eso también es broma!\p"
	.string "Bueno, ahora fuera de bromas:\n"
	.string "no soy demasiado bueno combatiendo.\p"
	.string "¿Por qué no me dejas ser tu aprendiz\n"
	.string "y me enseñas algo sobre los POKéMON?$"

gText_ApprenticeRejectTeaching10::
	.string "Si vas a ir por ahí pasando de todo,\n"
	.string "¡vas a ver lo que hago yo!\p"
	.string "¡Buaaaa! ¡Buaaaa! ¡Buaaaa!\n"
	.string "¡Snif! ¡Buaaaa! ¡Buaaaa!\p"
	.string "¡Ja, ja, ja, ja! ¡Ése es mi LLANTO FALSO!\p"
	.string "Vamos, venga, que no se diga.\n"
	.string "¿Me dejas ser tu aprendiz?$"

gText_ApprenticeWhichLevelMode10::
	.string "¡Yupi!\n"
	.string "¡Te voy a regalar un yate!\p"
	.string "¡Bueno, otro día, claro!\n"
	.string "Pero… ¡gracias, mi capitán!\p"
	.string "Ya sabes que hay un nivel 50 y un nivel\n"
	.string "libre en la TORRE BATALLA, ¿verdad?\p"
	.string "Es que tengo problemas para decidirme\n"
	.string "en cuál de los dos debería participar…\p"
	.string "¿Cuál elegirías en mi lugar?$"

gText_ApprenticeLevelModeThanks10::
	.string "Vale, conque el {STR_VAR_1}.\n"
	.string "Entonces me apunto al otro, ¿no?\p"
	.string "¡Es broma!\n"
	.string "¡Te haré caso!\p"
	.string "¡Gracias!\n"
	.string "¡Espero que sigas instruyéndome!$"

gText_ApprenticePleaseTeach11::
	.string "¡Hola, hola, hola,\n"
	.string "dijo el mar a la caracola!\p"
	.string "¡Me llamo {STR_VAR_1}, soy soltero,\n"
	.string "mal poeta y buen MARINERO!\p"
	.string "¡Dime algo de ti, hombre,\n"
	.string "aunque sólo sea tu nombre!\p"
	.string "¡Mmm! ¡{PLAYER}{KUN} dices llamarte,\n"
	.string "y que te gusta de POKéMON rodearte!\p"
	.string "¡Ah, qué edad la tuya más tierna,\n"
	.string "en la que la vida parece eterna!\p"
	.string "Bueno, de suerte creo que estoy,\n"
	.string "pues contigo ya son 10\l"
	.string "los ENTRENADORES que he visto hoy.\p"
	.string "Y, ya puestos, vamos a rematarlo.\n"
	.string "¡Hazme tu aprendiz para celebrarlo!$"

gText_ApprenticeRejectTeaching11::
	.string "Será broma, espero…\n"
	.string "¿O acaso rehúsas a un caballero?\p"
	.string "¡No me dejes con mal sabor!\n"
	.string "¡Hazme tu aprendiz, por favor!$"

gText_ApprenticeWhichLevelMode11::
	.string "¡Eso es! ¡Qué alegría! ¡Qué alegría!\n"
	.string "¡{PLAYER}, me has animado el día!\p"
	.string "¡Aconséjame sobre la TORRE BATALLA,\n"
	.string "porque mi buen juicio a veces me falla!\p"
	.string "Nivel 50 o nivel libre: debo elegir.\n"
	.string "¿En cuál me debería inscribir?$"

gText_ApprenticeLevelModeThanks11::
	.string "Vale, el {STR_VAR_1} me aconsejas.\n"
	.string "¡Una duda que me despejas!\p"
	.string "¡Aquí vendré si necesito otro consejo!\n"
	.string "¡Hasta entonces, {PLAYER}, te dejo!$"

gText_ApprenticePleaseTeach12::
	.string "¡Ey! ¿{PLAYER}? ¿Eres tú?\n"
	.string "¡Pues claro! “¡Only you!”\p"
	.string "Tranqui, {PLAYER}, no estoy loco.\n"
	.string "¡Es la música, que me absorbe el coco!\p"
	.string "Llámame {STR_VAR_1} si quieres,\n"
	.string "no rey de la guitarra, si lo prefieres.\p"
	.string "Sí, no, sí, no, probando, probando.\n"
	.string "¡Te diré lo que quiero cantando!\p"
	.string "{PLAYER}, voy a echarle valor,\n"
	.string "y te voy a pedir un favor.\p"
	.string "¡“Please”, déjame ser tu aprendiz!\n"
	.string "¡No habría nadie en el mundo tan feliz!$"

gText_ApprenticeRejectTeaching12::
	.string "No me digas que no, te lo pido.\n"
	.string "¡Las baladas tristes no son mi estilo!\p"
	.string "¡“Please”, déjame ser tu aprendiz!\n"
	.string "¡No habría nadie en el mundo tan feliz!$"

gText_ApprenticeWhichLevelMode12::
	.string "“¡Ou, yea!” ¡Y ya que soy tu aprendiz!\n"
	.string "¿Por qué no me ayudas a decidir?\p"
	.string "En la TORRE BATALLA, siempre tengo\n"
	.string "una duda que nunca falla.\p"
	.string "De los niveles que vas a ver,\n"
	.string "¿cuál crees que debo escoger?$"

gText_ApprenticeLevelModeThanks12::
	.string "En el {STR_VAR_1} que me sugieres,\n"
	.string "prometo hacer bien los deberes.\p"
	.string "¡{PLAYER}, fue un placer encontrarte!\n"
	.string "¡Me largo con la música a otra parte!$"

gText_ApprenticePleaseTeach13::
	.string "¡Oh, hola! ¡Qué tal!\n"
	.string "¿Me das un masaje en el hombro?…\p"
	.string "¡Sí, ahí! ¡Justo ahí!\n"
	.string "¡Ay! ¡Ah! ¡Oh! ¡Oooh! ¡Mucho mejor!\p"
	.string "Me llamo {STR_VAR_1}.\n"
	.string "Voy a clases de karate, pero creo que\l"
	.string "mi cuerpo no está hecho para sufrir…\p"
	.string "He decidido combatir con POKéMON,\n"
	.string "así al menos yo no me haré daño.\p"
	.string "Tú eres {PLAYER}{KUN}, ¿a que sí?\n"
	.string "¿Verdad que has conseguido un\l"
	.string "CAMPEONATO de la LIGA POKéMON?\p"
	.string "Oye, ¿por qué no te animas a darme\n"
	.string "consejos en plan maestro y aprendiz?$"

gText_ApprenticeRejectTeaching13::
	.string "Oh, ¿y por qué no?\p"
	.string "¡No te daré la lata, de verdad!\n"
	.string "¿Anda, por favor?$"

gText_ApprenticeWhichLevelMode13::
	.string "Muchas gracias. ¡Es un detallazo!\n"
	.string "¡Achís! ¡Achís!\p"
	.string "Ay, tengo que curarme esto…\p"
	.string "Voy a participar ahora mismo en la\n"
	.string "TORRE BATALLA, pero ¿qué crees que me\l"
	.string "convendría más? ¿El nivel 50 o el libre?$"

gText_ApprenticeLevelModeThanks13::
	.string "Ah, vale, el {STR_VAR_1}.\n"
	.string "Me largo ahora mismo.\p"
	.string "¡Espero poder seguir contando\n"
	.string "con tu ayuda!$"

gText_ApprenticePleaseTeach14::
	.string "Esto… Mm…\n"
	.string "¿{PLAYER}{KUN}?…\p"
	.string "Anda, por favor, no me mires así.\n"
	.string "Me vas a sacar los colores.\p"
	.string "Yo… soy {STR_VAR_1}.\p"
	.string "Suena un poco pretencioso y así, pero\n"
	.string "yo me dedico a explorar ruinas, ¿sabes?\p"
	.string "Aunque puede que hasta suene\n"
	.string "más pretencioso querer participar\l"
	.string "en el FRENTE de BATALLA…\p"
	.string "{PLAYER}{KUN}, tú tienes fama de saber\n"
	.string "entrenar duro…\p"
	.string "No quería soltártelo así de repente,\n"
	.string "pero no me queda otro remedio.\p"
	.string "¿Querrías tomarme como aprendiz\n"
	.string "tuyo y darme consejos?$"

gText_ApprenticeRejectTeaching14::
	.string "¡Por favor, no me rechaces!\n"
	.string "Llevo fatal lo de las humillaciones.\p"
	.string "¡Anda, déjame ser tu aprendiz!\n"
	.string "¡Necesito tus consejos!$"

gText_ApprenticeWhichLevelMode14::
	.string "Gra-gracias…\p"
	.string "Pero no me mires más con esa cara\n"
	.string "o sólo tendrás un aprendiz frustrado.\p"
	.string "Anda, respóndeme a esta pregunta,\n"
	.string "pero sin mirarme a los ojos.\p"
	.string "En la TORRE BATALLA…\n"
	.string "¿en qué nivel debería inscribirme?$"

gText_ApprenticeLevelModeThanks14::
	.string "Oh… ¡Vale!\n"
	.string "Probaré en ése, a ver qué tal.\p"
	.string "Espero combatir de manera digna para\n"
	.string "que no tengas que avergonzarte de mí…\p"
	.string "Bueno, gracias, {PLAYER}{KUN}.\n"
	.string "Ojalá nos veamos pronto otra vez.\l"
	.string "¡Estos consejos tuyos son geniales!$"

gText_ApprenticePleaseTeach15::
	.string "¿Mm? Vaya, pareces ser {PLAYER}{KUN}…\n"
	.string "Pero me pregunto si serás real…\p"
	.string "Mi nombre es {STR_VAR_1}.\p"
	.string "Estoy sopesando la idea de continuar\n"
	.string "mi aprendizaje bajo los auspicios.\l"
	.string "de un ENTRENADOR de fama reconocida.\p"
	.string "¡Me congratula pues verte ahora aquí!…\n"
	.string "Porque de verdad eres {PLAYER}{KUN}, ¿no?\p"
	.string "No, no, si eres {PLAYER}{KUN}, está bien.\n"
	.string "Tan sólo quisiera que considerases\l"
	.string "tomarme como tu aprendiz.$"

gText_ApprenticeRejectTeaching15::
	.string "¡Oh!\n"
	.string "¿Qué te habrá empujado a rechazarme?\p"
	.string "Siento haberme mostrado tan escéptico\n"
	.string "sobre tu verdadera identidad.\p"
	.string "Te ruego aceptes mis disculpas\n"
	.string "y me tomes como tu aprendiz.$"

gText_ApprenticeWhichLevelMode15::
	.string "¿Realmente me aceptas de aprendiz?\n"
	.string "No querría lanzar las campanas al vuelo.\p"
	.string "Si es verdad, perdona las dudas que\n"
	.string "expresé antes sobre tu identidad.\l"
	.string "Pero ahora, necesito de tu consejo.\p"
	.string "Si fuese a entrar en la TORRE BATALLA,\n"
	.string "¿qué nivel sería digno de mí?,\l"
	.string "¿el nivel 50 o el nivel libre?$"

gText_ApprenticeLevelModeThanks15::
	.string "¿{STR_VAR_1}?\n"
	.string "¿Es ésa tu conclusión?\p"
	.string "Bien. Confiaré en tu buen juicio.\n"
	.string "Tienes todo mi agradecimiento.\p"
	.string "Soy consciente de lo pesado que puedo\n"
	.string "resultar, por eso lo agradezco aún más.\p"
	.string "Sería todo un placer volver a verte!\n"
	.string "Ahora, si me disculpas…$"

gText_ApprenticeWhatHeldItem0::
	.string "Ay… Ay…\n"
	.string "¡Oh, {PLAYER}!\p"
	.string "Tengo un dilema y no sé qué hacer.\p"
	.string "No me decido sobre qué objeto debe\n"
	.string "sostener mi {STR_VAR_1}.\p"
	.string "¿Tú qué opinas, {PLAYER}?\n"
	.string "¿Qué objeto debería sostener?$"

gText_ApprenticeHoldNothing0::
	.string "¿Ah, sí? ¿Crees que es mejor que mi\n"
	.string "{STR_VAR_1} no sostenga ningún objeto?$"

gText_ApprenticeThanksNoHeldItem0::
	.string "¡Ah, vale! ¡Pues entonces ya está!\n"
	.string "¡Genial! ¡Alucinante! ¡Superguay!\p"
	.string "¡Muchísimas gracias!$"

gText_ApprenticeThanksHeldItem0::
	.string "Ah, muy bien…\n"
	.string "Sí, tengo eso que llamas {STR_VAR_1}.\p"
	.string "¡Una preocupación menos!\n"
	.string "¡Genial! ¡Alucinante! ¡Superguay!\p"
	.string "¡Muchísimas gracias!$"

gText_ApprenticeItemAlreadyRecommended0::
	.string "¡Buaaaa! ¡Anda, no seas así!\p"
	.string "Eso que llamas {STR_VAR_1} ya me\n"
	.string "suena de haberlo oído antes…\p"
	.string "¿O me quieres decir que {STR_VAR_2}\n"
	.string "no debería sostener nada?$"

gText_ApprenticeWhatHeldItem1::
	.string "¡Yupi! ¡Pero si eres {PLAYER}!\n"
	.string "¡Genial! ¡Quería preguntarte algo!\p"
	.string "¿Tus POKéMON sostienen objetos?\n"
	.string "Quiero que el mío sostenga uno, pero…\p"
	.string "¿Cuál crees que le convendría más\n"
	.string "sostener a {STR_VAR_1}?\p"
	.string "¿Tú qué piensas?$"

gText_ApprenticeHoldNothing1::
	.string "¿Cómo? ¿Quieres decir que es mejor\n"
	.string "que mi {STR_VAR_1} no sostenga nada?$"

gText_ApprenticeThanksNoHeldItem1::
	.string "¡Vale, lo he pillado!\n"
	.string "¡Gracias por enseñarme!$"

gText_ApprenticeThanksHeldItem1::
	.string "Conque {STR_VAR_1}, ¿eh?\n"
	.string "¡Vale, lo he pillado!\p"
	.string "¡Gracias por enseñarme!$"

gText_ApprenticeItemAlreadyRecommended1::
	.string "Ah, no, eso no es lo que quería.\n"
	.string "Quería que me dijeses un objeto\l"
	.string "distinto de los que ya conozco.\p"
	.string "¿O me estás queriendo decir que no\n"
	.string "debería sujetar nada mi POKéMON?$"

gText_ApprenticeWhatHeldItem2::
	.string "¡{PLAYER}, hola!\n"
	.string "Es sobre mi {STR_VAR_1}…\p"
	.string "Quiero que sostenga algún objeto.\n"
	.string "¿Cuál le vendría mejor?$"

gText_ApprenticeHoldNothing2::
	.string "Ah, ¿entonces crees que no tiene\n"
	.string "que sostener nada mi {STR_VAR_1}?$"

gText_ApprenticeThanksNoHeldItem2::
	.string "¡Vale, lo he entendido!\n"
	.string "¡Nos vemos!$"

gText_ApprenticeThanksHeldItem2::
	.string "Oh, ¿{STR_VAR_1}?\n"
	.string "¡Entendido!\p"
	.string "¡Haré lo que pueda por encontrar eso!\n"
	.string "¡Hasta otra!$"

gText_ApprenticeItemAlreadyRecommended2::
	.string "Lo de {STR_VAR_1} ya me suena\n"
	.string "que me lo han dicho antes.\p"
	.string "Pero yo quiero que mi POKéMON\n"
	.string "sostenga algo distinto.\p"
	.string "¿O piensas que mi {STR_VAR_2}\n"
	.string "no debería sostener nada?$"

gText_ApprenticeWhatHeldItem3::
	.string "Hola, {PLAYER}…\n"
	.string "Perdona que te moleste, pero hay\l"
	.string "algo más que quería preguntarte.\p"
	.string "No creo que sea muy buena ganando\n"
	.string "solita los combates, y estaba pensando\l"
	.string "en que {STR_VAR_1} podía sostener algo.\p"
	.string "Pero no sé qué objeto le vendría mejor.\p"
	.string "{PLAYER}, porfa, ¿me ayudas?$"

gText_ApprenticeHoldNothing3::
	.string "¿Crees que, teniendo en cuenta a quién\n"
	.string "pertenece, sería mejor que mi POKéMON\l"
	.string "no sostuviese ningún objeto?$"

gText_ApprenticeThanksNoHeldItem3::
	.string "Ya veo… Quieres decir que no debo\n"
	.string "confiar demasiado en los objetos, ¿eh?\p"
	.string "¡Haré lo posible por no confiar en ellos!\n"
	.string "¡Gracias mil!$"

gText_ApprenticeThanksHeldItem3::
	.string "Uf, {STR_VAR_1}, vale.\n"
	.string "No va a ser fácil conseguir algo así…\l"
	.string "Pero haré lo que pueda.\p"
	.string "¡Gracias mil!$"

gText_ApprenticeItemAlreadyRecommended3::
	.string "Oh, pero…\n"
	.string "Eso ya me lo han recomendado…\p"
	.string "¿A lo mejor es que no sé manejar\n"
	.string "bien ninguna clase de {STR_VAR_1}?\p"
	.string "¿O me quieres decir realmente que\n"
	.string "{STR_VAR_2} no debería sostener nada?$"

gText_ApprenticeWhatHeldItem4::
	.string "Oh, {PLAYER}{KUN}.\n"
	.string "Tenía ganas de preguntarte una cosa.\p"
	.string "¿Te acuerdas de que una vez me dijiste\n"
	.string "qué clase de POKéMON debería entrenar?\p"
	.string "Pues es que se te olvidó decirme\n"
	.string "qué clase de objeto debería sostener.\p"
	.string "Ya que te decidiste a darme un consejo,\n"
	.string "no quiero que lo dejes a medias, claro.\p"
	.string "Anda, dime, ¿qué objeto debería\n"
	.string "sostener mi {STR_VAR_1}?$"

gText_ApprenticeHoldNothing4::
	.string "¡Ah! ¿Conque a mi {STR_VAR_1}\n"
	.string "le irá mejor si no lleva nada?$"

gText_ApprenticeThanksNoHeldItem4::
	.string "Si de verdad piensas que es lo mejor,\n"
	.string "haré lo que dices.\p"
	.string "Sabiendo que me lo has dicho tú,\n"
	.string "{PLAYER}{KUN}, no me enfadaré si pierdo.\p"
	.string "Bueno, ya te pediré otro consejo\n"
	.string "otro día. ¡Chao!$"

gText_ApprenticeThanksHeldItem4::
	.string "Así que {STR_VAR_1}, ¿eh?\n"
	.string "¡No está mal! ¡Tomo nota!\p"
	.string "Sabiendo que me lo has dicho tú,\n"
	.string "{PLAYER}{KUN}, no me enfadaré si pierdo.\p"
	.string "Bueno, ya te pediré otro consejo\n"
	.string "otro día. ¡Chao!$"

gText_ApprenticeItemAlreadyRecommended4::
	.string "¿Cómo? Pero ¿de qué hablas?\n"
	.string "No me vengas otra vez con lo de\l"
	.string "{STR_VAR_1}.\p"
	.string "¿O quieres decir que a {STR_VAR_2}\n"
	.string "le iría mejor si no llevase nada?$"

gText_ApprenticeWhatHeldItem5::
	.string "¡Mira quién está aquí!\n"
	.string "¡{PLAYER}{KUN}!\p"
	.string "Puede que tengamos mucho que hacer,\n"
	.string "¡pero siempre nos encontramos!\p"
	.string "Hoy he estado todo el día de aquí\npara allá.\p"
	.string "Ni siquiera he tenido tiempo de comprar\n"
	.string "nada a mi precioso {STR_VAR_1}.\p"
	.string "Oye, ¿por qué no me aconsejas\n"
	.string "algún objeto que le pueda venir bien?$"

gText_ApprenticeHoldNothing5::
	.string "Oh, así que, como tengo tanto lío, ¿no\n"
	.string "tengo que buscarle nada a {STR_VAR_1}?$"

gText_ApprenticeThanksNoHeldItem5::
	.string "Vale, ya sé por dónde vas.\n"
	.string "¡Así no perderé el tiempo de compras!\p"
	.string "¡Gracias!\n"
	.string "¡Ya nos veremos!$"

gText_ApprenticeThanksHeldItem5::
	.string "{STR_VAR_1}, vale, entiendo.\n"
	.string "A ver si puedo sacar un rato libre\l"
	.string "y me voy a comprar eso que dices.\p"
	.string "Me alegro de ser tu aprendiz.\n"
	.string "¡Gracias! ¡Ya nos veremos!$"

gText_ApprenticeItemAlreadyRecommended5::
	.string "¿Eh? Lo de {STR_VAR_1} ya me suena\n"
	.string "de haberlo oído antes.\p"
	.string "¡Ah, ya! ¡Ahora pillo la indirecta!\n"
	.string "Que no pierda el tiempo en comprarle\l"
	.string "nada a {STR_VAR_2}, ¿no?$"

gText_ApprenticeWhatHeldItem6::
	.string "¡{PLAYER}! ¡Soy yo!\n"
	.string "Necesito tu coco otra vez.\l"
	.string "¡Tienes que darme un consejo!\p"
	.string "¡Iré al grano!\n"
	.string "Mi pregunta es…\p"
	.string "Si quiero que mi {STR_VAR_1} sostenga\n"
	.string "un objeto, ¿cuál me recomendarías?$"

gText_ApprenticeHoldNothing6::
	.string "¿Seguro? Que mejor que mi {STR_VAR_1}\n"
	.string "no sostenga nada, dices, ¿eh?$"

gText_ApprenticeThanksNoHeldItem6::
	.string "¡Muy bien, con eso es suficiente!\p"
	.string "Es todo lo que quería preguntarte.\p"
	.string "Nos vemos aquí otra vez, ¿vale?\n"
	.string "¡Gracias!$"

gText_ApprenticeThanksHeldItem6::
	.string "¡Anda! ¡{STR_VAR_1}!\n"
	.string "¿Cómo no se me había ocurrido antes?\l"
	.string "¡Voy a probar ahora mismo con eso!\p"
	.string "Es todo lo que quería preguntarte.\p"
	.string "Nos vemos aquí otra vez, ¿vale?\n"
	.string "¡Gracias!$"

gText_ApprenticeItemAlreadyRecommended6::
	.string "¡Ja, ja, ja! ¡Qué tontería!\n"
	.string "¡Eso de {STR_VAR_1} ya me lo habías\l"
	.string "dicho antes!\p"
	.string "¿Seguro que estás bien, {PLAYER}?\p"
	.string "¡Espera! ¡Era una indirecta para decirme\n"
	.string "que {STR_VAR_2} no debería llevar nada!$"

gText_ApprenticeWhatHeldItem7::
	.string "Hola, {PLAYER}.\n"
	.string "¿Te va todo bien?\p"
	.string "¿Podría solicitar otra vez uno\n"
	.string "de tus maravillosos consejos?\p"
	.string "En mi último combate, creo que mi rival\n"
	.string "le dio un objeto a su POKéMON\l"
	.string "para que lo sostuviera.\p"
	.string "Creo que perdí por ese dichoso objeto…\p"
	.string "No quiero quedarme atrás.\n"
	.string "Yo también quiero que mi {STR_VAR_1}\l"
	.string "sostenga un objeto.\p"
	.string "Te agradecería mucho si me dijeses\n"
	.string "cuál le convendría más…$"

gText_ApprenticeHoldNothing7::
	.string "En otras palabras… , que mi POKéMON\n"
	.string "no necesita llevar ningún objeto…$"

gText_ApprenticeThanksNoHeldItem7::
	.string "¡Pues claro! ¡Ahora lo entiendo!\n"
	.string "Seguiré combatiendo como hasta ahora.\p"
	.string "Gracias, {PLAYER}.\n"
	.string "Espero poder contar contigo otra vez.\l"
	.string "Te me cuidas mucho, ¿vale?$"

gText_ApprenticeThanksHeldItem7::
	.string "¡{STR_VAR_1}! ¡Entendido!\n"
	.string "¡Ahora mismo voy a pedir lo que me dices!\p"
	.string "Gracias, {PLAYER}.\n"
	.string "Espero poder contar contigo otra vez.\l"
	.string "Te me cuidas mucho, ¿vale?$"

gText_ApprenticeItemAlreadyRecommended7::
	.string "¡Eso ya me lo dijiste\n"
	.string "y además ya lo tengo!\p"
	.string "¿O me estás diciendo que mi POKéMON\n"
	.string "no necesita llevar ningún objeto?$"

gText_ApprenticeWhatHeldItem8::
	.string "¡Hooola, {PLAYER}!\n"
	.string "¡Qu-qué alegría verte!\p"
	.string "¡Oh-oh-oh! ¡Ya sé! ¡Voy a preguntarte\n"
	.string "algo ahorita mismo, {PLAYER}!\p"
	.string "¡Dime qué objeto crees que\n"
	.string "debería sostener mi {STR_VAR_1}!$"

gText_ApprenticeHoldNothing8::
	.string "¡Oh, vaya! ¡Eso no me lo esperaba!\n"
	.string "¿Así que no tiene que llevar nada?$"

gText_ApprenticeThanksNoHeldItem8::
	.string "¡Lo he entendido a la primera!\n"
	.string "¡Seguiré luchando sin objetos!\p"
	.string "Espero que no te olvides\n"
	.string "de seguir enseñándome cosas, ¿eh?$"

gText_ApprenticeThanksHeldItem8::
	.string "¡{STR_VAR_1}! ¡Por supuestísimo!\p"
	.string "Mmm… ¿No será, {PLAYER}, que tu POKéMON\n"
	.string "también sostiene ese objeto?\p"
	.string "¡Da igual! ¡Te haré caso!\n"
	.string "Espero que no te olvides\l"
	.string "de seguir enseñándome cosas, ¿eh?$"

gText_ApprenticeItemAlreadyRecommended8::
	.string "¿Cómo? ¿{STR_VAR_1}? ¿Otra vez?\n"
	.string "¡Pero eso ya me lo recomendaste antes!\p"
	.string "Una de dos, o te gusta mucho,\n"
	.string "o me estás diciendo que mi {STR_VAR_2}\l"
	.string "no necesita llevar ningún objeto…$"

gText_ApprenticeWhatHeldItem9::
	.string "¡Hola! ¡{PLAYER}{KUN}!\n"
	.string "¡Qué ganas tenía de verte!\p"
	.string "Necesito que me aconsejes\n"
	.string "sobre los objetos POKéMON.\p"
	.string "¿Cuál crees que sería mejor\n"
	.string "que sostuviese mi {STR_VAR_1}?\p"
	.string "No te cortes.\n"
	.string "¡Venga, suéltalo!$"

gText_ApprenticeHoldNothing9::
	.string "¿Eh? ¿Así que mi {STR_VAR_1}\n"
	.string "no debería llevar nada?$"

gText_ApprenticeThanksNoHeldItem9::
	.string "¡Vale, vale!\n"
	.string "¡Lo intentaré como dices, a ver qué tal!\p"
	.string "¡Muy bien, gracias, como siempre!\n"
	.string "¡Adiós!$"

gText_ApprenticeThanksHeldItem9::
	.string "¿{STR_VAR_1}? ¡Vale, vale!\n"
	.string "¡A ver si pillo algo de eso!\p"
	.string "¡Muy bien, gracias, como siempre!\n"
	.string "¡Adiós!$"

gText_ApprenticeItemAlreadyRecommended9::
	.string "¡No, no! ¡Eso ya lo has dicho antes!\n"
	.string "¡Sí, me acuerdo! ¡{STR_VAR_1}!\p"
	.string "Alto ahí… ¿No me estarás diciendo que\n"
	.string "{STR_VAR_2} puede ganar sin objetos?$"

gText_ApprenticeWhatHeldItem10::
	.string "¡{PLAYER}{KUN}, ha pasado algo increíble!\p"
	.string "¡Cuando me levanté esta mañana,\n"
	.string "mi POKéMON tenía 10 PEPITAS!\p"
	.string "¡Que no, que es broma!\n"
	.string "¡Ja, ja, ja, ja!\p"
	.string "Ahora en serio: no sé qué objeto\n"
	.string "debería sostener mi POKéMON.\p"
	.string "¿Por qué no decides tú por mí?\n"
	.string "¿Qué le doy a mi {STR_VAR_1}?$"

gText_ApprenticeHoldNothing10::
	.string "¿Qué significa eso?\n"
	.string "¿Que no sostenga nada?$"

gText_ApprenticeThanksNoHeldItem10::
	.string "Okay, so it shouldn't hold anything.\n"
	.string "Then, I'd better get something for it!\p"
	.string "Just kidding!\n"
	.string "I'll obey your teaching, master!\p"
	.string "Thanks, master!\n"
	.string "I hope you'll keep teaching me!$"

gText_ApprenticeThanksHeldItem10::
	.string "Okay, so it's one {STR_VAR_1}!\n"
	.string "I'll make it hold anything but that!\p"
	.string "Just kidding!\n"
	.string "I'll obey your teaching, master!\p"
	.string "Thanks, master!\n"
	.string "I hope you'll keep teaching me!$"

gText_ApprenticeItemAlreadyRecommended10::
	.string "Um, you told me about that before,\n"
	.string "didn't you?\p"
	.string "Isn't there something else?\p"
	.string "Or do you mean, don't make\n"
	.string "my {STR_VAR_2} hold anything?$"

gText_ApprenticeWhatHeldItem11::
	.string "A-H-O-Y!\n"
	.string "And that spells ahoy!\p"
	.string "The rappin' SAILOR am I!\n"
	.string "I present to you a question\l"
	.string "that's pretty fly!\p"
	.string "It's an item question\n"
	.string "that begs your suggestion!\p"
	.string "My {STR_VAR_1} needs an item to hold,\n"
	.string "What should it be, if I may be bold?$"

gText_ApprenticeHoldNothing11::
	.string "Is that right?\n"
	.string "My {STR_VAR_1} doesn't need to be\l"
	.string "holding anything tight?$"

gText_ApprenticeThanksNoHeldItem11::
	.string "Okay, I hear you, sure I do!\n"
	.string "My POKéMON will go empty-handed, too!\p"
	.string "If it's advice I ever need,\n"
	.string "{PLAYER}, your word I'll always heed!$"

gText_ApprenticeThanksHeldItem11::
	.string "Okay, one {STR_VAR_1},\n"
	.string "that's what I'll use.\l"
	.string "I was right to make you choose!\p"
	.string "If it's advice I ever need,\n"
	.string "{PLAYER}, your word I'll always heed!$"

gText_ApprenticeItemAlreadyRecommended11::
	.string "Okay, one {STR_VAR_1}, you say?\n"
	.string "You told me that the other day.\l"
	.string "I need a new idea, a brand new way.\p"
	.string "Or, what, is that right?\n"
	.string "My POKéMON doesn't need to hold\l"
	.string "anything tight?$"

gText_ApprenticeWhatHeldItem12::
	.string "Say, hey, {PLAYER}!\n"
	.string "I found you again today!\p"
	.string "What should I do? Get your advice?\n"
	.string "Why not? I'm already talking to you!\p"
	.string "{PLAYER}, are you getting sick of me?\n"
	.string "Nah, no way, that can't be.\p"
	.string "Will you hear me out?\n"
	.string "I'm looking for advice--that's what\l"
	.string "I'm talking about.\p"
	.string "It's about a hold item for\n"
	.string "my {STR_VAR_1} that'd be good.\l"
	.string "My indecision is making me brood.$"

gText_ApprenticeHoldNothing12::
	.string "My {STR_VAR_1} needs nothing?\n"
	.string "Doesn't need to hold anything?$"

gText_ApprenticeThanksNoHeldItem12::
	.string "If holding nothing is the best,\n"
	.string "I'll do as you suggest!\p"
	.string "Well, {PLAYER}, I have to roam free,\n"
	.string "but don't you forget about me.\p"
	.string "See you again, my smart friend!$"

gText_ApprenticeThanksHeldItem12::
	.string "If holding that {STR_VAR_1} is\n"
	.string "the best, I'll do as you suggest!\p"
	.string "Well, {PLAYER}, I have to roam free,\n"
	.string "but don't you forget about me.\p"
	.string "See you again, my smart friend!$"

gText_ApprenticeItemAlreadyRecommended12::
	.string "Haven't I heard about that\n"
	.string "{STR_VAR_1} before?\l"
	.string "I'm certain I have, that's for sure!\p"
	.string "I need a new something!\n"
	.string "Or, my {STR_VAR_2} needs nothing?\l"
	.string "Doesn't need to hold anything?$"

gText_ApprenticeWhatHeldItem13::
	.string "Gwah! Ouch! {PLAYER}{KUN}, my arm's broken!\n"
	.string "Don't touch it, please!\p"
	.string "I must've broken it while I was trying\n"
	.string "out different hold items with my posse\l"
	.string "of POKéMON.\p"
	.string "So, things being this way,\n"
	.string "I need you to decide for me.\p"
	.string "{PLAYER}{KUN}, what do you think would be\n"
	.string "good for my {STR_VAR_1} to hold?$"

gText_ApprenticeHoldNothing13::
	.string "Ouch…\p"
	.string "So your suggestion is my {STR_VAR_1}\n"
	.string "doesn't have to hold anything?$"

gText_ApprenticeThanksNoHeldItem13::
	.string "Hm, all right. That would be easier\n"
	.string "for me, the way things are now.\p"
	.string "I hope I can keep hitting you up\n"
	.string "for help like this.$"

gText_ApprenticeThanksHeldItem13::
	.string "Hm, all right. That's one {STR_VAR_1}.\n"
	.string "My POKéMON's arm is fine, so I'll make\l"
	.string "it hold that item right away.\p"
	.string "I hope I can keep hitting you up\n"
	.string "for help like this.$"

gText_ApprenticeItemAlreadyRecommended13::
	.string "No, no, you told me about that\n"
	.string "{STR_VAR_1} before, remember?\p"
	.string "How about telling me something\n"
	.string "even better?\p"
	.string "Oh, wait a second.\n"
	.string "So your suggestion is my {STR_VAR_2}\l"
	.string "doesn't have to hold anything?$"

gText_ApprenticeWhatHeldItem14::
	.string "Er… Um…\n"
	.string "{PLAYER}{KUN}…\p"
	.string "Please, don't look at me that way.\n"
	.string "My POKéMON don't have anything.\p"
	.string "I… I'm really embarrassed about this,\n"
	.string "but I really need your advice.\p"
	.string "I can't decide what hold item would\n"
	.string "make my {STR_VAR_1} strong.\p"
	.string "{PLAYER}{KUN}, what do you think would\n"
	.string "be good?$"

gText_ApprenticeHoldNothing14::
	.string "Oh… Then, you think it would be better\n"
	.string "if my {STR_VAR_1} didn't have an item?$"

gText_ApprenticeThanksNoHeldItem14::
	.string "Oh… Okay!\n"
	.string "I'll go without an item.\p"
	.string "This is nerve-racking, though.\n"
	.string "Wouldn't it be too cool?\p"
	.string "Thank you, {PLAYER}{KUN}.\n"
	.string "If we meet again, I hope you will be\l"
	.string "as helpful.$"

gText_ApprenticeThanksHeldItem14::
	.string "Oh… Okay!\n"
	.string "I'll go with that {STR_VAR_1}.\p"
	.string "This is nerve-racking, though.\n"
	.string "Wouldn't it be too cool?\p"
	.string "Thank you, {PLAYER}{KUN}.\n"
	.string "If we meet again, I hope you will be\l"
	.string "as helpful.$"

gText_ApprenticeItemAlreadyRecommended14::
	.string "B-but I already heard about that.\p"
	.string "Please don't brush me off like this!\n"
	.string "I can't live with the humiliation.\p"
	.string "Oh… Am I jumping to conclusions?\n"
	.string "Do you think it would be better if\l"
	.string "my {STR_VAR_2} didn't have an item?$"

gText_ApprenticeWhatHeldItem15::
	.string "Hm? You appear to be {PLAYER}{KUN}…\n"
	.string "But are you really?\l"
	.string "Perhaps you're a twin?\p"
	.string "Oh, no, no, no, don't worry!\n"
	.string "If you really are {PLAYER}, please\l"
	.string "forget about my rudeness.\p"
	.string "What I would like is some more of\n"
	.string "your fine advice.\p"
	.string "I have here my {STR_VAR_1} that I wish\n"
	.string "to make hold a convenient item.\p"
	.string "What would be worthy of it?$"

gText_ApprenticeHoldNothing15::
	.string "It's better if it held nothing?\n"
	.string "Are you certain?$"

gText_ApprenticeThanksNoHeldItem15::
	.string "I see. If that's the case, that's fine.\n"
	.string "I thank you for your time.\p"
	.string "Let us meet again!$"

gText_ApprenticeThanksHeldItem15::
	.string "One {STR_VAR_1}?\n"
	.string "Are you certain?\p"
	.string "I see. If that's the case, that's fine.\n"
	.string "I thank you for your time.\p"
	.string "I do hope my POKéMON will be able to\n"
	.string "put it to good use.\p"
	.string "Let us meet again!$"

gText_ApprenticeItemAlreadyRecommended15::
	.string "No, no, wait a minute.\n"
	.string "I believe you taught me that before.\p"
	.string "I would like you to recommend\n"
	.string "something different this time.\p"
	.string "Perhaps you're suggesting that\n"
	.string "my {STR_VAR_2} should hold nothing?\l"
	.string "Are you certain?$"

gText_ApprenticeWhichMonFirst0::
	.string "Waah, {PLAYER}!\n"
	.string "I have a dilemma, sob…\p"
	.string "I want to begin battling other people,\n"
	.string "but I don't know what to do.\p"
	.string "How should I line up my POKéMON\n"
	.string "so they'll be at their strongest?\p"
	.string "Please tell me, {PLAYER}.\n"
	.string "If you were me, which of these POKéMON\l"
	.string "would you send out first?$"

gText_ApprenticeMonFirstThanks0::
	.string "My {STR_VAR_1} should go first?\n"
	.string "Waaaaah!\p"
	.string "Oh! I'm so sorry!\n"
	.string "You've made me happy by choosing\l"
	.string "my first POKéMON, and it's made me cry…\p"
	.string "Thank you so much!$"

gText_ApprenticeWhichMonFirst1::
	.string "Yay! It's {PLAYER}!\n"
	.string "Great! I wanted to ask you something!\p"
	.string "Um, of my POKéMON, which do you\n"
	.string "think should go out first?$"

gText_ApprenticeMonFirstThanks1::
	.string "My {STR_VAR_1}? That's true.\n"
	.string "Okay, I'll do that!\p"
	.string "Thanks for teaching me!$"

gText_ApprenticeWhichMonFirst2::
	.string "{PLAYER}, hello!\p"
	.string "I think, in a battle, it's very important\n"
	.string "which POKéMON comes out first.\p"
	.string "Out of the POKéMON that I have,\n"
	.string "which would be good to send out first?$"

gText_ApprenticeMonFirstThanks2::
	.string "My {STR_VAR_1} goes first?\n"
	.string "Okay, I got it!\p"
	.string "See you again!$"

gText_ApprenticeWhichMonFirst3::
	.string "Hello, {PLAYER}…\n"
	.string "I'm sorry to disturb you again with\l"
	.string "another question.\p"
	.string "I have so little confidence, I don't\n"
	.string "know what I'd do without you, {PLAYER}.\p"
	.string "It may be a waste of time for me to\n"
	.string "even worry about it, but I just can't\l"
	.string "decide something…\p"
	.string "Which of my POKéMON should I send\n"
	.string "out first in a battle?$"

gText_ApprenticeMonFirstThanks3::
	.string "My {STR_VAR_1}?\n"
	.string "Understood!\p"
	.string "I can't believe that you would bother\n"
	.string "to answer my questions so often!\p"
	.string "I'm so grateful that you would even\n"
	.string "speak with me… Thank you!$"

gText_ApprenticeWhichMonFirst4::
	.string "Oh, {PLAYER}{KUN}! It's me!\n"
	.string "I'm so glad to see you because I have\l"
	.string "this little problem.\p"
	.string "I can't decide how my POKéMON should\n"
	.string "be lined up. Could you decide for me?\p"
	.string "Oh, you don't need to decide the whole\n"
	.string "party right now.\p"
	.string "How about deciding just the first\n"
	.string "POKéMON for me?$"

gText_ApprenticeMonFirstThanks4::
	.string "My {STR_VAR_1}? That's great!\p"
	.string "Knowing that you made the decision,\n"
	.string "{PLAYER}{KUN}, I won't be so upset if\l"
	.string "I lose.\p"
	.string "Okay, I'll look to you for advice again.\n"
	.string "Bye!$"

gText_ApprenticeWhichMonFirst5::
	.string "Hi, my teacher {PLAYER}{KUN}!\n"
	.string "I'm busy again today!\p"
	.string "I have to do some cycling, shopping,\n"
	.string "and humming.\p"
	.string "I haven't even had the time to decide\n"
	.string "how to line up my POKéMON team.\p"
	.string "So, how about checking out my team?\n"
	.string "Which one should go first?$"

gText_ApprenticeMonFirstThanks5::
	.string "Okay, gotcha.\n"
	.string "I have enough time at least to put\l"
	.string "my {STR_VAR_1} at the head of the line!\p"
	.string "Whoops, my girlfriend's waiting!\n"
	.string "Thanks! See you around!$"

gText_ApprenticeWhichMonFirst6::
	.string "Yoohoo! Hiya, {PLAYER}!\n"
	.string "You always walk around looking tough!\p"
	.string "Listen, I need something from you\n"
	.string "again! It's the usual thing!\p"
	.string "Drum roll, please!\n"
	.string "The question I have is about my team.\p"
	.string "Which POKéMON of mine should be first\n"
	.string "to go out in a battle?$"

gText_ApprenticeMonFirstThanks6::
	.string "Hmhm!\n"
	.string "My {STR_VAR_1}, you say!\l"
	.string "Thanks for a most cool answer!\p"
	.string "I guess that's about all I wanted\n"
	.string "to ask you today.\p"
	.string "Let's meet here again, okay?\n"
	.string "Thanks!$"

gText_ApprenticeWhichMonFirst7::
	.string "Thank you so much for stopping to\n"
	.string "chat with me, {PLAYER}.\p"
	.string "I know I'm taking advantage of your\n"
	.string "kindness, but may I ask for advice?\p"
	.string "I would like you to decide on the order\n"
	.string "of my POKéMON team.\p"
	.string "It would please me if you could decide\n"
	.string "which POKéMON should come first.$"

gText_ApprenticeMonFirstThanks7::
	.string "My {STR_VAR_1} it is!\n"
	.string "I will put it first right away!\p"
	.string "Thank you, {PLAYER}.\n"
	.string "I hope I can count on you again.\l"
	.string "Please take care!$"

gText_ApprenticeWhichMonFirst8::
	.string "Eek! {PLAYER}!\n"
	.string "I… I'm overjoyed to see you again!\p"
	.string "My POKéMON have become much\n"
	.string "stronger!\p"
	.string "But I don't always win. It seems to\n"
	.string "depend on which POKéMON goes first.\p"
	.string "{PLAYER}, please, I need your help!\p"
	.string "Please decide which of my POKéMON\n"
	.string "should go out first!$"

gText_ApprenticeMonFirstThanks8::
	.string "Sigh… I'm overwhelmed with happiness…\p"
	.string "It's like a dream having you decide\n"
	.string "for me, {PLAYER}.\p"
	.string "But perfectly understood!\n"
	.string "I will go with my {STR_VAR_1} first!\p"
	.string "I hope you'll be willing to teach me\n"
	.string "some more another time.$"

gText_ApprenticeWhichMonFirst9::
	.string "Hello, hello!\n"
	.string "My mentor, {PLAYER}{KUN}!\l"
	.string "Hit me with your sage advice today!\p"
	.string "You see, I pulled together a team of\n"
	.string "three POKéMON. So far so good.\p"
	.string "But the team's battling order's not\n"
	.string "settled yet.\p"
	.string "This is where you come in, {PLAYER}{KUN}!\n"
	.string "You decide which POKéMON leads off!\p"
	.string "Don't be shy now.\n"
	.string "Let's blurt it out!$"

gText_ApprenticeMonFirstThanks9::
	.string "Uh-huh, my {STR_VAR_1} leads off!\n"
	.string "OK, A-OK!\l"
	.string "I'll reorder the lineup, like, wham!\p"
	.string "All right, thanks, as always!\n"
	.string "Adios!$"

gText_ApprenticeWhichMonFirst10::
	.string "{PLAYER}{KUN}, listen!\n"
	.string "It's a crisis!\p"
	.string "My POKéMON, all three of them, go into\n"
	.string "battle at once!\p"
	.string "Of course that's impossible!\n"
	.string "Wahahaha!\p"
	.string "This is no lie, though.\n"
	.string "I'm not very good at thinking about\l"
	.string "how I should line up my POKéMON.\p"
	.string "So, how about deciding for me which\n"
	.string "POKéMON should go first, master?$"

gText_ApprenticeMonFirstThanks10::
	.string "Okay, so it's my {STR_VAR_1} you chose?\n"
	.string "I'll let any but that one go first!\p"
	.string "Just kidding!\n"
	.string "I'll obey your teaching, master!\p"
	.string "Thanks, master!\n"
	.string "I hope you'll keep teaching me!$"

gText_ApprenticeWhichMonFirst11::
	.string "A-H-O-Y!\n"
	.string "And that spells ahoy!\p"
	.string "The rappin' SAILOR am I!\n"
	.string "I present to you a question\l"
	.string "that's pretty fly!\p"
	.string "It's a team lineup question\n"
	.string "that begs your suggestion!\p"
	.string "Out of this lot, which should go first\n"
	.string "as the first on the spot?$"

gText_ApprenticeMonFirstThanks11::
	.string "Okay, I hear you, sure I do!\n"
	.string "I'll switch them up, that I'll do!\p"
	.string "If it's advice I ever need,\n"
	.string "{PLAYER}, your word I'll always heed!$"

gText_ApprenticeWhichMonFirst12::
	.string "Yahoo, {PLAYER}!\n"
	.string "How do you do?\p"
	.string "What should I do? Go ahead and ask?\n"
	.string "Uh-huh, I have something to ask!\l"
	.string "Are you receiving me?\l"
	.string "You are receiving me!\p"
	.string "You have to decide, which of my\n"
	.string "POKéMON is the first to ride!\l"
	.string "Into battle, I mean to say.$"

gText_ApprenticeMonFirstThanks12::
	.string "My {STR_VAR_1}? Yes!\n"
	.string "That'll do, there's no distress!\p"
	.string "Well, {PLAYER}, I have to roam free,\n"
	.string "but don't you forget about me.\p"
	.string "See you again, my smart friend!$"

gText_ApprenticeWhichMonFirst13::
	.string "…Oof…ooch… {PLAYER}{KUN}…\n"
	.string "My stomach's hurting all of a sudden…\p"
	.string "…It's getting better now…\p"
	.string "I must've worried myself sick racking\n"
	.string "my brains on how I should line up\l"
	.string "my posse of POKéMON.\p"
	.string "So, things being this way,\n"
	.string "I need you to decide for me.\p"
	.string "{PLAYER}{KUN}, which of my POKéMON should\n"
	.string "go first? So I'd win, I mean.$"

gText_ApprenticeMonFirstThanks13::
	.string "Hm, all right.\n"
	.string "My {STR_VAR_1} goes first.\p"
	.string "I'll fix the lineup like that after\n"
	.string "I have my supper.\p"
	.string "I hope I can keep hitting you up\n"
	.string "for help like this.$"

gText_ApprenticeWhichMonFirst14::
	.string "Er… Um…\n"
	.string "{PLAYER}{KUN}?\p"
	.string "Please, don't look at me that way.\n"
	.string "You're making me feel all flustered.\p"
	.string "Um…\n"
	.string "I really need your advice.\p"
	.string "It makes me bashful to say this,\n"
	.string "but I chose my 3-POKéMON team.\l"
	.string "I can't decide on the order, though.\p"
	.string "Which POKéMON should I send out first\n"
	.string "so I at least look capable?$"

gText_ApprenticeMonFirstThanks14::
	.string "Oh… Okay!\n"
	.string "I'll lead with my {STR_VAR_1}.\p"
	.string "I hope I can do my best without\n"
	.string "getting all flustered.\p"
	.string "Thank you, {PLAYER}{KUN}.\n"
	.string "If we meet again, I hope you will be\l"
	.string "as helpful.$"

gText_ApprenticeWhichMonFirst15::
	.string "Hm? You appear to be {PLAYER}{KUN}…\n"
	.string "But are you really?\l"
	.string "Perhaps you're a clever look-alike?\p"
	.string "Oh, no, no, no, don't worry!\n"
	.string "If you really are {PLAYER}, please\l"
	.string "forget about my rudeness.\p"
	.string "What I would like is your fine advice.\p"
	.string "I have here my POKéMON team.\n"
	.string "I would like you to tell me which one\l"
	.string "should go first in a battle.$"

gText_ApprenticeMonFirstThanks15::
	.string "My {STR_VAR_1}…\n"
	.string "You aren't pulling my leg?\p"
	.string "I see. If that's the case, that's fine.\n"
	.string "I thank you for your time.\p"
	.string "I am as you see, but I shall do\n"
	.string "my best.\p"
	.string "Let us meet again!$"

gText_ApprenticeWhichMon0::
	.string "Snivel…\n"
	.string "Oh, {PLAYER}!\p"
	.string "What perfect timing!\n"
	.string "There's something I just can't decide…\p"
	.string "I can't decide which POKéMON I should\n"
	.string "be using.\p"
	.string "I can't decide between the POKéMON\n"
	.string "{STR_VAR_1} and {STR_VAR_2}…\p"
	.string "{PLAYER}, which do you think will give\n"
	.string "even me a chance at winning?$"

gText_ApprenticeMonThanks0::
	.string "Snivel… I… I understand!\n"
	.string "Oh! I'm so sorry!\l"
	.string "You've made me so happy, I'm crying…\p"
	.string "I'll do my best to catch one\n"
	.string "{STR_VAR_1}!\p"
	.string "Thank you so much!$"

gText_ApprenticeWhichMon1::
	.string "Yay! It's {PLAYER}!\n"
	.string "Yay, you came at the right time, too!\l"
	.string "I need your advice again!\p"
	.string "Um, I'm all mixed up--should I use\n"
	.string "my {STR_VAR_1} or {STR_VAR_2}…\p"
	.string "Which do you think I should raise,\n"
	.string "{PLAYER}?$"

gText_ApprenticeMonThanks1::
	.string "Oh, so my {STR_VAR_1} is better!\n"
	.string "Okay, I'll do that!\p"
	.string "Thanks for teaching me!$"

gText_ApprenticeWhichMon2::
	.string "{PLAYER}, hello!\n"
	.string "I have a question I wanted to ask.\p"
	.string "I'm in a dilemma over whether I should\n"
	.string "raise one {STR_VAR_1} or {STR_VAR_2}.\p"
	.string "Which POKéMON do you think will\n"
	.string "be stronger?$"

gText_ApprenticeMonThanks2::
	.string "{STR_VAR_1} is your choice?\n"
	.string "Okay, I got it!\p"
	.string "I'll go catch a strong {STR_VAR_1}\n"
	.string "right away!\p"
	.string "See you again!$"

gText_ApprenticeWhichMon3::
	.string "Hello, {PLAYER}…\p"
	.string "Um, you've probably already forgotten\n"
	.string "about someone like me…\p"
	.string "…But that doesn't matter if you\n"
	.string "could give me advice…\p"
	.string "I can't decide on the one kind of\n"
	.string "POKéMON I should raise…\p"
	.string "I've narrowed the field to the POKéMON\n"
	.string "{STR_VAR_1} and {STR_VAR_2}, but that's\l"
	.string "where I became stuck…\p"
	.string "{PLAYER}, you probably don't want to\n"
	.string "bother, but please decide for me.$"

gText_ApprenticeMonThanks3::
	.string "But will a wild {STR_VAR_1} even pay\n"
	.string "attention to me?\p"
	.string "I will try!\p"
	.string "But will I even be able to catch one…\n"
	.string "No! I'll do my best!\p"
	.string "Thank you!$"

gText_ApprenticeWhichMon4::
	.string "Oh, {PLAYER}{KUN}! I'm so glad to see you!\n"
	.string "I was about to go looking for you!\p"
	.string "Can you decide what kind of POKéMON\n"
	.string "I should use?\p"
	.string "For instance…\n"
	.string "How about the POKéMON {STR_VAR_1}\l"
	.string "and {STR_VAR_2}?\p"
	.string "Which one do you think would be\n"
	.string "better?$"

gText_ApprenticeMonThanks4::
	.string "{STR_VAR_1}? That's great!\p"
	.string "Knowing that you made the decision,\n"
	.string "{PLAYER}{KUN}, I won't be so upset if\l"
	.string "I lose.\p"
	.string "Okay, I'll look to you for advice again.\n"
	.string "Bye!$"

gText_ApprenticeWhichMon5::
	.string "If it isn't {PLAYER}{KUN}! How's it going?\n"
	.string "I'm busy again as always!\p"
	.string "I want to do good with POKéMON, too,\n"
	.string "but I haven't been able to decide\l"
	.string "which POKéMON I should use.\p"
	.string "You know how {STR_VAR_1} look strong?\n"
	.string "But {STR_VAR_2} are tough to ignore.\p"
	.string "{PLAYER}{KUN}, give me some of your good\n"
	.string "advice! Which one'd be good for me?$"

gText_ApprenticeMonThanks5::
	.string "Okay, gotcha.\n"
	.string "I'll find time somehow and catch me\l"
	.string "that {STR_VAR_1} you recommended.\p"
	.string "I'm glad I met a good mentor in you.\n"
	.string "Thanks! See you around!$"

gText_ApprenticeWhichMon6::
	.string "Oh!\n"
	.string "Yay, it's {PLAYER}!\p"
	.string "I didn't waste any time boasting to\n"
	.string "my friends about meeting you!\p"
	.string "I need to tap your mind again today.\n"
	.string "It's an easy one for you!\p"
	.string "Drum roll, please!\n"
	.string "The question I have is…\p"
	.string "If I were to raise a POKéMON,\n"
	.string "and the choices were one {STR_VAR_1}\l"
	.string "or {STR_VAR_2}, which should it be?$"

gText_ApprenticeMonThanks6::
	.string "Ahhh!\n"
	.string "{STR_VAR_1}, you say!\l"
	.string "Thanks for a most cool answer!\p"
	.string "I guess that's about all I wanted\n"
	.string "to ask you today.\p"
	.string "Let's meet here again, okay?\n"
	.string "Thanks!$"

gText_ApprenticeWhichMon7::
	.string "Oh, is it you, {PLAYER}?\n"
	.string "I'm delighted to see you again!\p"
	.string "Ever since I became your apprentice,\n"
	.string "my confidence has been blooming.\p"
	.string "I think I'm ready to raise a POKéMON\n"
	.string "of my own!\p"
	.string "{PLAYER}, may I impose on you to choose\n"
	.string "which POKéMON I should raise?\p"
	.string "The choices are the POKéMON\n"
	.string "{STR_VAR_1} or {STR_VAR_2}…\l"
	.string "Which POKéMON is right for me?$"

gText_ApprenticeMonThanks7::
	.string "One {STR_VAR_1} it is!\n"
	.string "I will find one right away!\p"
	.string "Thank you, {PLAYER}.\n"
	.string "I hope I can count on you again.\l"
	.string "Please take care!$"

gText_ApprenticeWhichMon8::
	.string "Eek! {PLAYER}! I met you again!\n"
	.string "I… I'm overjoyed!\p"
	.string "Oh-oh-oh, I know!\n"
	.string "I shouldn't pass up this opportunity!\p"
	.string "May I ask a huge favor, {PLAYER}?\n"
	.string "Please choose a POKéMON for me!\p"
	.string "Please decide which would be better,\n"
	.string "{STR_VAR_1} or {STR_VAR_2}!$"

gText_ApprenticeMonThanks8::
	.string "Wow! You decided for me!\n"
	.string "One {STR_VAR_1} is what I'll raise to\l"
	.string "the best of my ability.\p"
	.string "I hope you'll be willing to teach me\n"
	.string "some more another time.$"

gText_ApprenticeWhichMon9::
	.string "Hey, hey!\n"
	.string "My mentor, {PLAYER}{KUN}!\p"
	.string "Hello, I've been looking for you\n"
	.string "for some more of your sage advice!\p"
	.string "Which kind of POKéMON would be right\n"
	.string "for me, one {STR_VAR_1} or {STR_VAR_2}?\p"
	.string "Don't be shy now.\n"
	.string "Let's blurt it out!$"

gText_ApprenticeMonThanks9::
	.string "Uh-huh, one {STR_VAR_1} it is!\n"
	.string "OK, A-OK!\l"
	.string "I'll get one in a BALL, like, cram!\p"
	.string "All right, thanks, as always!\n"
	.string "Adios!$"

gText_ApprenticeWhichMon10::
	.string "{PLAYER}{KUN}, listen! Big news!\n"
	.string "I caught a mirage POKéMON!\p"
	.string "Of course I'm lying!\n"
	.string "Wahahaha!\p"
	.string "This is no lie, though.\n"
	.string "I'm not very good at catching\l"
	.string "POKéMON.\p"
	.string "So, how about deciding for me which\n"
	.string "kind of POKéMON I should catch,\l"
	.string "master?\p"
	.string "Which would be better?\n"
	.string "{STR_VAR_1} or {STR_VAR_2}?$"

gText_ApprenticeMonThanks10::
	.string "Okay, so it's {STR_VAR_1} you chose?\n"
	.string "I'll grab the other kind, then!\p"
	.string "Just kidding!\n"
	.string "I'll obey your teaching, master!\p"
	.string "Thanks, master!\n"
	.string "I hope you'll keep teaching me!$"

gText_ApprenticeWhichMon11::
	.string "A-H-O-Y!\n"
	.string "And that spells ahoy!\p"
	.string "The rappin' SAILOR am I!\n"
	.string "Surely you remember who am I?\p"
	.string "Today, I have a POKéMON question\n"
	.string "that begs your suggestion!\p"
	.string "I have the choice between this\n"
	.string "{STR_VAR_1} and {STR_VAR_2}, you see.\l"
	.string "Which is the one to catch for me?$"

gText_ApprenticeMonThanks11::
	.string "{STR_VAR_1}, you say, hey, hey!\n"
	.string "I'll go get me one right away!\p"
	.string "If it's advice I ever need,\n"
	.string "{PLAYER}, your word I'll always heed!$"

gText_ApprenticeWhichMon12::
	.string "Oh, wow, if it isn't {PLAYER}!\p"
	.string "What should I do? Get your advice?\n"
	.string "Why not? I'm already talking to you!\p"
	.string "It's been a long time. Let me break\n"
	.string "the ice. I'm also looking for advice!\l"
	.string "Are you receiving me?\l"
	.string "You are receiving me!\p"
	.string "My POKéMON--which should I use?\n"
	.string "It's either {STR_VAR_1} or {STR_VAR_2}.\l"
	.string "Which do you choose?$"

gText_ApprenticeMonThanks12::
	.string "If that {STR_VAR_1} is the best,\n"
	.string "I'll do as you suggest!\p"
	.string "Well, {PLAYER}, I have to roam free,\n"
	.string "but don't you forget about me.\p"
	.string "See you again, my smart friend!$"

gText_ApprenticeWhichMon13::
	.string "Oh, hi, {PLAYER}{KUN}…\n"
	.string "I have this horrible headache…\p"
	.string "I must've worried too much about\n"
	.string "the kind of POKéMON I should raise.\p"
	.string "So, things being this way,\n"
	.string "I need you to decide for me.\p"
	.string "{PLAYER}{KUN}, if I had to choose between\n"
	.string "the POKéMON {STR_VAR_1} and\l"
	.string "{STR_VAR_2}, which should it be?$"

gText_ApprenticeMonThanks13::
	.string "Hm, one {STR_VAR_1}, all right.\n"
	.string "I'll go look for one when I get better.\p"
	.string "I hope I can keep hitting you up\n"
	.string "for help like this.$"

gText_ApprenticeWhichMon14::
	.string "Er… Um…\n"
	.string "{PLAYER}{KUN}…?\p"
	.string "Please, don't look at me that way.\n"
	.string "I'm getting all flustered…\l"
	.string "I… I need your advice.\p"
	.string "I… I'm really embarrassed, but I can't\n"
	.string "decide which POKéMON to use.\p"
	.string "If the choices were {STR_VAR_1} or\n"
	.string "{STR_VAR_2}, which would be better?$"

gText_ApprenticeMonThanks14::
	.string "Oh… Okay!\n"
	.string "I'll do my best with one {STR_VAR_1}.\p"
	.string "I hope I can do my best without\n"
	.string "getting all flustered.\p"
	.string "Thank you, {PLAYER}{KUN}.\n"
	.string "If we meet again, I hope you will be\l"
	.string "as helpful.$"

gText_ApprenticeWhichMon15::
	.string "Hm? You appear to be {PLAYER}{KUN}…\n"
	.string "But are you really real?\p"
	.string "No, no, if you are real, it's fine.\n"
	.string "Incidentally, I would like to obtain\l"
	.string "your advice.\p"
	.string "It's about the POKéMON I am to use.\p"
	.string "If the choices are the POKéMON\n"
	.string "{STR_VAR_1} and {STR_VAR_2}, which is\l"
	.string "more worthy of me?$"

gText_ApprenticeMonThanks15::
	.string "{STR_VAR_1}?\n"
	.string "Are you certain?\p"
	.string "I see. If that's the case, that's fine.\n"
	.string "I thank you for your time.\p"
	.string "I do hope it is something even I can\n"
	.string "handle with aplomb.\p"
	.string "Let us meet again!$"

gText_ApprenticeWhichMove0::
	.string "Waaah! Oh, {PLAYER}!\n"
	.string "Snivel… Hiccup…\p"
	.string "I have a dilemma!\n"
	.string "I can't decide on a move for\l"
	.string "my {STR_VAR_1}…\p"
	.string "Please, please, {PLAYER}.\n"
	.string "Can you decide for me?\p"
	.string "For my {STR_VAR_1}, which move would\n"
	.string "be the better choice: {STR_VAR_2}\l"
	.string "or {STR_VAR_3}?$"

gText_ApprenticeMoveThanks0::
	.string "{STR_VAR_1}?\n"
	.string "Waaaaah!\p"
	.string "Oh! I'm so sorry, {PLAYER}!\n"
	.string "You've made me so happy by deciding\l"
	.string "the move, I'm crying…\p"
	.string "Snivel…\n"
	.string "Thank you so much!$"

gText_ApprenticeWhichMove1::
	.string "Yay! Hi, {PLAYER}!\n"
	.string "I need your advice again!\p"
	.string "I want to teach my {STR_VAR_1}\n"
	.string "a cool move.\p"
	.string "I like either of the moves\n"
	.string "{STR_VAR_2} or {STR_VAR_3}.\l"
	.string "What's your recommendation?$"

gText_ApprenticeMoveThanks1::
	.string "{STR_VAR_1} is better? I guess so!\n"
	.string "Okay, I'll go with that!\p"
	.string "If we meet here again, please teach\n"
	.string "me something else, teacher!$"

gText_ApprenticeWhichMove2::
	.string "{PLAYER}, hello!\n"
	.string "It's about my {STR_VAR_1}, but I'm\l"
	.string "worried about its moves.\p"
	.string "You see, it's the moves {STR_VAR_2}\n"
	.string "and {STR_VAR_3}.\p"
	.string "Which is stronger and better for\n"
	.string "my {STR_VAR_1}?$"

gText_ApprenticeMoveThanks2::
	.string "{STR_VAR_1} is your choice?\n"
	.string "Okay, I got it!\p"
	.string "I'll go teach {STR_VAR_1} to\n"
	.string "my POKéMON right away!\p"
	.string "See you again!$"

gText_ApprenticeWhichMove3::
	.string "Ohhh, {PLAYER}…\n"
	.string "I'm hopeless, no, really!\p"
	.string "I've decided to raise a POKéMON,\n"
	.string "but now I can't even decide what\l"
	.string "move I should let it learn…\p"
	.string "I know that it doesn't mean anything\n"
	.string "to you, {PLAYER}.\p"
	.string "But it means a lot to me…\p"
	.string "Please, {PLAYER}, could you choose\n"
	.string "a move for my {STR_VAR_1}?\p"
	.string "If you could even choose between\n"
	.string "{STR_VAR_2} and {STR_VAR_3}…$"

gText_ApprenticeMoveThanks3::
	.string "I understand!\p"
	.string "But will it even be willing to learn\n"
	.string "{STR_VAR_1} for me…\l"
	.string "No! I'll do my best!\p"
	.string "Thank you!$"

gText_ApprenticeWhichMove4::
	.string "Oh, {PLAYER}{KUN}!\n"
	.string "I was just hoping to see you, too!\p"
	.string "I was wondering what move would\n"
	.string "be suitable for my {STR_VAR_1}.\p"
	.string "I can't decide, so can you decide\n"
	.string "for me instead?\p"
	.string "For instance… How about the moves\n"
	.string "{STR_VAR_2} and {STR_VAR_3}?\l"
	.string "Which one would be better?$"

gText_ApprenticeMoveThanks4::
	.string "{STR_VAR_1}? That's great!\p"
	.string "Knowing that you made the decision,\n"
	.string "{PLAYER}{KUN}, I won't be so upset if\l"
	.string "I lose.\p"
	.string "Okay, I'll look to you for advice again.\n"
	.string "Bye!$"

gText_ApprenticeWhichMove5::
	.string "How could things be this busy?\n"
	.string "Hey, if it isn't {PLAYER}{KUN}!\l"
	.string "How's it going?\p"
	.string "Since I got up this morning, I've done\n"
	.string "my jogging, swimming, and cooking!\p"
	.string "You wouldn't believe how busy I am!\p"
	.string "I can't even decide what move\n"
	.string "my {STR_VAR_1} should learn!\p"
	.string "{STR_VAR_2} looks good, huh?\n"
	.string "But {STR_VAR_3}'s also decent.\p"
	.string "{PLAYER}{KUN}, give me some of your good\n"
	.string "advice! Which move'd be good for me?$"

gText_ApprenticeMoveThanks5::
	.string "Okay, gotcha.\n"
	.string "I'll make room in my schedule and\l"
	.string "teach that move.\p"
	.string "I'm glad I met a good mentor in you.\n"
	.string "Thanks! See you around!$"

gText_ApprenticeWhichMove6::
	.string "Oh! Lucky!\n"
	.string "I met you again, {PLAYER}!\l"
	.string "I need to tap your mind again today.\p"
	.string "Drum roll, please!\n"
	.string "The question I have is…\p"
	.string "For my {STR_VAR_1}, which is the move\n"
	.string "best suited, {STR_VAR_2} or\l"
	.string "{STR_VAR_3}?$"

gText_ApprenticeMoveThanks6::
	.string "Ahhh!\n"
	.string "{STR_VAR_1}, you say!\l"
	.string "Thanks for a most cool answer!\p"
	.string "I guess that's about all I wanted\n"
	.string "to ask you today.\p"
	.string "Let's meet here again, okay?\n"
	.string "Thanks!$"

gText_ApprenticeWhichMove7::
	.string "Oh, hello, {PLAYER}.\n"
	.string "I trust you've been well?\p"
	.string "I have to seek your advice again.\n"
	.string "It's about my dearest {STR_VAR_1}.\p"
	.string "What would be the ideal move for\n"
	.string "my lovable {STR_VAR_1}?\l"
	.string "{STR_VAR_2} or {STR_VAR_3}?$"

gText_ApprenticeMoveThanks7::
	.string "{STR_VAR_1} it is!\n"
	.string "I will teach that right away!\p"
	.string "Thank you, {PLAYER}.\n"
	.string "I hope I can count on you again.\l"
	.string "Please take care!$"

gText_ApprenticeWhichMove8::
	.string "Eek! {PLAYER}! I met you again!\n"
	.string "I… I'm overjoyed!\p"
	.string "Whenever I'm in need, you're always\n"
	.string "there for me, {PLAYER}!\p"
	.string "Today, I want you to recommend\n"
	.string "a move for me!\p"
	.string "Please choose a move for\n"
	.string "my {STR_VAR_1}!\p"
	.string "Which move would be better,\n"
	.string "{STR_VAR_2} or {STR_VAR_3}?$"

gText_ApprenticeMoveThanks8::
	.string "Oh-oh-oh! Thank you!\n"
	.string "{STR_VAR_1} is it!\l"
	.string "Perfectly understood!\p"
	.string "I hope you'll be willing to teach me\n"
	.string "some more another time.$"

gText_ApprenticeWhichMove9::
	.string "Hola, {PLAYER}{KUN}, bueno!\n"
	.string "I'm hoping for some more of\l"
	.string "your sage advice today!\p"
	.string "What would be the best move for\n"
	.string "my {STR_VAR_1}?\p"
	.string "It should be something that'll\n"
	.string "let me win just like that!\p"
	.string "Would it be {STR_VAR_2}?\n"
	.string "Or {STR_VAR_3}?$"

gText_ApprenticeMoveThanks9::
	.string "Uh-huh, {STR_VAR_1} it is!\n"
	.string "Si, bueno!\l"
	.string "I'll get it taught, like, ka-blam!\p"
	.string "All right, thanks, as always!\n"
	.string "Adios!$"

gText_ApprenticeWhichMove10::
	.string "{PLAYER}{KUN}, it's completely wild!\p"
	.string "My POKéMON!\n"
	.string "It learned six moves!\p"
	.string "Of course I'm lying!\n"
	.string "Wahahaha!\p"
	.string "This is no lie, though.\n"
	.string "I'm not very good at choosing moves\l"
	.string "for my POKéMON.\p"
	.string "So, how about deciding for me which\n"
	.string "kind of move I should teach?\p"
	.string "{STR_VAR_2} or {STR_VAR_3}--which\n"
	.string "would go with my {STR_VAR_1} best?$"

gText_ApprenticeMoveThanks10::
	.string "Okay, so it's {STR_VAR_1} you chose?\n"
	.string "I'll choose another move, then!\p"
	.string "Just kidding!\n"
	.string "I'll obey your teaching, master!\p"
	.string "Thanks, master!\n"
	.string "I hope you'll keep teaching me!$"

gText_ApprenticeWhichMove11::
	.string "A-H-O-Y!\n"
	.string "And that spells ahoy!\p"
	.string "The rappin' SAILOR am I!\n"
	.string "I'm always with it, don't ask me why.\p"
	.string "Today, I have a move question\n"
	.string "that begs your suggestion!\p"
	.string "{STR_VAR_2} and {STR_VAR_3} are\n"
	.string "the moves. What would be the best\l"
	.string "for my {STR_VAR_1} so it grooves?$"

gText_ApprenticeMoveThanks11::
	.string "{STR_VAR_1}, you say, hey, hey!\n"
	.string "I'll go teach that right away!\p"
	.string "If it's advice I ever need,\n"
	.string "{PLAYER}, your word I'll always heed!$"

gText_ApprenticeWhichMove12::
	.string "Oh, yeahah, if it isn't {PLAYER}!\p"
	.string "What should I do? Get your advice?\n"
	.string "Why not? I'm already talking to you!\p"
	.string "{PLAYER}, are you surprised by me?\n"
	.string "I want your advice, can't you see?\p"
	.string "Are you receiving me?\n"
	.string "You are receiving me!\p"
	.string "My {STR_VAR_1}--what should it use?\n"
	.string "It's {STR_VAR_2} or {STR_VAR_3},\l"
	.string "what do you choose?$"

gText_ApprenticeMoveThanks12::
	.string "If that {STR_VAR_1} is the best,\n"
	.string "I'll do as you suggest!\p"
	.string "Well, {PLAYER}, I have to roam free,\n"
	.string "but don't you forget about me.\p"
	.string "See you again, my smart friend!$"

gText_ApprenticeWhichMove13::
	.string "Gahack! Gaah! Oh, {PLAYER}{KUN}…\n"
	.string "I have this lousy cold, I do…\p"
	.string "I want to pick a move for my POKéMON,\n"
	.string "but I'm not up to it…\p"
	.string "So, things being this way,\n"
	.string "I need you to decide for me.\p"
	.string "{PLAYER}{KUN}, if I had to choose between\n"
	.string "{STR_VAR_2} and {STR_VAR_3} for\l"
	.string "my {STR_VAR_1}, which would it be?$"

gText_ApprenticeMoveThanks13::
	.string "Hm, {STR_VAR_1}, all right. Cough!\n"
	.string "I'll go teach it when I get better.\p"
	.string "I hope I can keep hitting you up\n"
	.string "for help like this.$"

gText_ApprenticeWhichMove14::
	.string "Er… Um…\n"
	.string "{PLAYER}{KUN}…?\p"
	.string "Please, don't look at me that way.\n"
	.string "I'm getting all flustered…\l"
	.string "I… I need your advice.\p"
	.string "I… I'm really embarrassed, but I can't\n"
	.string "decide what move I should teach\l"
	.string "my POKéMON.\p"
	.string "It's for my {STR_VAR_1}.\n"
	.string "If the choices were {STR_VAR_2} or\l"
	.string "{STR_VAR_3}, which would be better?$"

gText_ApprenticeMoveThanks14::
	.string "Oh… Okay!\n"
	.string "I'll try that {STR_VAR_1}.\p"
	.string "I hope I can teach that move…\n"
	.string "This is so nerve-racking…\p"
	.string "Thank you, {PLAYER}{KUN}.\n"
	.string "If we meet again, I hope you will be\l"
	.string "as helpful.$"

gText_ApprenticeWhichMove15::
	.string "Hm? You appear to be {PLAYER}{KUN}…\n"
	.string "But are you really real?\p"
	.string "Perhaps you're one of those popular\n"
	.string "mimics?\p"
	.string "No, no, if you are real, it's fine.\n"
	.string "No need to be upset, I assure you!\p"
	.string "Incidentally, I would like to obtain\n"
	.string "your advice.\p"
	.string "It's about my {STR_VAR_1}.\p"
	.string "Which move would be better for it to\n"
	.string "use, {STR_VAR_2} or {STR_VAR_3}?$"

gText_ApprenticeMoveThanks15::
	.string "{STR_VAR_1}?\n"
	.string "There's no question about that?\p"
	.string "I see. If that's the case, that's fine.\n"
	.string "I thank you for your time.\p"
	.string "I do hope it is something even\n"
	.string "my POKéMON can learn.\p"
	.string "Let us meet again!$"

gText_ApprenticePickWinSpeech0::
	.string "Oh… {PLAYER}?\n"
	.string "It is {PLAYER}!\l"
	.string "Oh! Sniff…sob… Please, listen!\p"
	.string "I… When I battle, I get so nervous,\n"
	.string "I can't help crying even if I win…\p"
	.string "I wish I could say something cool\n"
	.string "when I win…\p"
	.string "Please, please, {PLAYER}!\n"
	.string "Could you maybe teach me something\l"
	.string "cool to say when I win so I don't cry?$"

gText_ApprenticeWinSpeechThanks0::
	.string "{STR_VAR_1}\p"
	.string "Awesome! Wicked! Awoooh!\n"
	.string "It's really cool!\p"
	.string "Oh… I'm sorry…\n"
	.string "I'm so happy, I'm crying…\p"
	.string "Snivel… {PLAYER}!\n"
	.string "Thank you so much for everything!\p"
	.string "I will battle the best I can for\n"
	.string "your sake, {PLAYER}!\p"
	.string "{PLAYER}…\n"
	.string "Next time… We should battle!$"

gText_ApprenticePickWinSpeech1::
	.string "Yay! It's {PLAYER}! Hello!\n"
	.string "I wanted to ask you something!\p"
	.string "I want to say something cool when\n"
	.string "I win a match.\p"
	.string "Do you have a cool saying that\n"
	.string "you could recommend?$"

gText_ApprenticeWinSpeechThanks1::
	.string "{STR_VAR_1}\p"
	.string "Oh, wow! That is so cool!\n"
	.string "Okay, I'll say that!\p"
	.string "Thanks for teaching me all this time!\n"
	.string "I'm going to do the best I can\l"
	.string "wherever I go from now on!\p"
	.string "When we meet again, it'll be for\n"
	.string "a battle!$"

gText_ApprenticePickWinSpeech2::
	.string "{PLAYER}, hello!\p"
	.string "My POKéMON and I are ready for\n"
	.string "anything, except for one thing.\p"
	.string "I think it would be good if I had\n"
	.string "something to shout when I win.\p"
	.string "Could you think up something good\n"
	.string "to say?$"

gText_ApprenticeWinSpeechThanks2::
	.string "{STR_VAR_1}\p"
	.string "…Cool!\n"
	.string "I will use that!\p"
	.string "I'm going out to battle all over\n"
	.string "the place.\p"
	.string "Who knows, I may even get to battle\n"
	.string "you one day, {PLAYER}.\p"
	.string "Next time, let's meet at a place\n"
	.string "of battle!$"

gText_ApprenticePickWinSpeech3::
	.string "Hello, {PLAYER}…\n"
	.string "I'm sorry to bug you, but I'm hopeless…\p"
	.string "Even when…\n"
	.string "Even when I win, I don't have anything\l"
	.string "special to say…\p"
	.string "I know that it doesn't mean anything\n"
	.string "to you, {PLAYER}.\p"
	.string "But it means a lot to me…\p"
	.string "Please, {PLAYER}, what should I say\n"
	.string "if I win a battle?$"

gText_ApprenticeWinSpeechThanks3::
	.string "{STR_VAR_1}\p"
	.string "That's inspired…\p"
	.string "Uh… Is it okay for someone like me\n"
	.string "to even say that?\p"
	.string "No! I'll do my best!\p"
	.string "{PLAYER}, thank you so much for\n"
	.string "putting up with me for so long…\p"
	.string "I promise to do my best from now on.\p"
	.string "I'm sure you'll quickly forget about\n"
	.string "someone like me, but let's meet\l"
	.string "somewhere again!$"

gText_ApprenticePickWinSpeech4::
	.string "Oh, {PLAYER}{KUN}.\n"
	.string "There's something I want you to hear.\p"
	.string "I know that I don't always sound\n"
	.string "nice or polite…\p"
	.string "When I win a battle, I think I come\n"
	.string "across as being arrogant.\p"
	.string "I don't want people to dislike me,\n"
	.string "so I want to say something nice to\l"
	.string "someone I beat.\p"
	.string "But I can't think of anything good!\n"
	.string "Could you think something up for me?$"

gText_ApprenticeWinSpeechThanks4::
	.string "{STR_VAR_1}\p"
	.string "Not bad!\n"
	.string "Yup, that's what I'll go with!\p"
	.string "I'm going to hit the road and do what\n"
	.string "I can with what you taught me in\l"
	.string "my head and heart.\p"
	.string "I'm sorry that I've been so pushy\n"
	.string "with you!\p"
	.string "Next time, we battle, okay?\n"
	.string "See you!$"

gText_ApprenticePickWinSpeech5::
	.string "Oh, I can't get over how busy I am!\n"
	.string "Oh, hey, I was looking for you, {PLAYER}{KUN}.\p"
	.string "Are you well as usual?\n"
	.string "Things haven't changed for me at all.\p"
	.string "I've got running, fighting, and mapping\n"
	.string "to do. Why am I so busy?\p"
	.string "But even though I'm busy, it'd be rude\n"
	.string "to just turn on my heels and walk away\l"
	.string "from a win without saying a word.\p"
	.string "So, what would be a cool saying to\n"
	.string "underline my coolness when I'm done\l"
	.string "and walking away? {PLAYER}{KUN}, help me!$"

gText_ApprenticeWinSpeechThanks5::
	.string "{STR_VAR_1}\p"
	.string "Okay, gotcha.\n"
	.string "I can find time to say that!\p"
	.string "Honestly, I'm glad I met a good mentor\n"
	.string "like you.\p"
	.string "I'm going to make time somehow so\n"
	.string "I can get into battling.\p"
	.string "Thanks for everything, {PLAYER}{KUN}!\n"
	.string "We have to battle, you and me, one day!$"

gText_ApprenticePickWinSpeech6::
	.string "I lucked out again!\n"
	.string "{PLAYER}! Am I glad to see you!\l"
	.string "Like usual, I need your advice!\p"
	.string "Drum roll, please!\n"
	.string "The last question I have is…\p"
	.string "If I win a battle and want to end\n"
	.string "it with a cool flourish, what\l"
	.string "should I say?$"

gText_ApprenticeWinSpeechThanks6::
	.string "{STR_VAR_1}\p"
	.string "That… That's fabulous!\n"
	.string "It's dignified and cool! I claim it!\p"
	.string "…Listen, I think I'm getting decent\n"
	.string "at this, huh?\p"
	.string "So, I'm thinking of challenging other\n"
	.string "TRAINERS from now on.\p"
	.string "{PLAYER}, your advice really helped me.\p"
	.string "Maybe one day, there'll be a time when\n"
	.string "we battle!\p"
	.string "Thank you for everything!$"

gText_ApprenticePickWinSpeech7::
	.string "Oh, {PLAYER}.\n"
	.string "I'm so glad I met you!\p"
	.string "I no longer have any concerns with\n"
	.string "regard to my POKéMON.\p"
	.string "It's myself that worries me…\p"
	.string "Do you know how a TRAINER says\n"
	.string "a few things upon winning a battle?\p"
	.string "Definitely, I wish I could do that,\n"
	.string "too!\p"
	.string "Please, what should I say when\n"
	.string "I win a battle?$"

gText_ApprenticeWinSpeechThanks7::
	.string "{STR_VAR_1}\p"
	.string "Ah! That saying! It refreshes me\n"
	.string "and makes me feel reborn!\p"
	.string "I must use that right away!\p"
	.string "And now, I must take my leave,\n"
	.string "{PLAYER}…\p"
	.string "I will go out to battle many others,\n"
	.string "but never will I forget your teachings.\p"
	.string "Perhaps one day…\n"
	.string "Farewell!$"

gText_ApprenticePickWinSpeech8::
	.string "Eek! I spotted {PLAYER}!\n"
	.string "I… I'm overjoyed to see you!\p"
	.string "Oh-oh-oh! There's something I just\n"
	.string "had to ask you!\p"
	.string "A little while ago, I won a battle.\n"
	.string "That part was giddying!\p"
	.string "But it made me so overjoyed that\n"
	.string "I choked up and couldn't say a thing!\p"
	.string "So now, {PLAYER}, please, I want you to\n"
	.string "think up an exit line for when I win!$"

gText_ApprenticeWinSpeechThanks8::
	.string "{STR_VAR_1}\p"
	.string "Waaaaah!\n"
	.string "I'm going to say that?!\l"
	.string "I… I'm delirious with joy!\p"
	.string "Th-th-thank you!\n"
	.string "I have nothing left to regret now!\p"
	.string "I'm going to travel now and battle\n"
	.string "all sorts of people.\p"
	.string "Everything, I owe it to you, {PLAYER}.\n"
	.string "Really, really, thank you!\p"
	.string "I've got to go now, but let's meet\n"
	.string "in battle one day!$"

gText_ApprenticePickWinSpeech9::
	.string "Hola, bueno!\n"
	.string "{PLAYER}{KUN}!\p"
	.string "You know, I'm getting the itch to roam\n"
	.string "and battle where I may.\p"
	.string "But before I do, I want your advice\n"
	.string "once again, please!\p"
	.string "If I were to win a battle, what would\n"
	.string "be a good boast I could say to my\l"
	.string "fallen TRAINER opponent?$"

gText_ApprenticeWinSpeechThanks9::
	.string "{STR_VAR_1}\p"
	.string "Uh-huh, that's sweet!\n"
	.string "Si, bueno!\l"
	.string "I'll try saying that, like, ham!\p"
	.string "And now, it's time to say good-bye!\n"
	.string "Thanks for all sorts of things!\p"
	.string "Give me a battle one day, OK?\n"
	.string "Adios!$"

gText_ApprenticePickWinSpeech10::
	.string "{PLAYER}{KUN}, there's big trouble!\p"
	.string "When I win a battle, I brag about it\n"
	.string "for an hour at least!\p"
	.string "Of course I'm lying!\n"
	.string "Wahahaha!\p"
	.string "This is no lie, though.\n"
	.string "I'm not very good at chatting.\p"
	.string "So, how about deciding for me what\n"
	.string "I should say after winning a battle,\l"
	.string "master?$"

gText_ApprenticeWinSpeechThanks10::
	.string "{STR_VAR_1}\p"
	.string "That's what I should say, huh?\n"
	.string "Then, I'll stay away from that!\p"
	.string "Just kidding!\n"
	.string "I'll obey your teaching, master!\p"
	.string "Thanks for teaching me all this time,\n"
	.string "master!\p"
	.string "I'm finally understanding what being\n"
	.string "a TRAINER is about.\p"
	.string "I'm going to go out and win battles\n"
	.string "against any TRAINER.\p"
	.string "Maybe it'll be you one day, master!\p"
	.string "That's all!\n"
	.string "Farewell, my master!$"

gText_ApprenticePickWinSpeech11::
	.string "A-H-O-Y!\n"
	.string "And that spells ahoy!\p"
	.string "The rappin' SAILOR am I!\n"
	.string "This will be my last question,\l"
	.string "don't you cry!\p"
	.string "It's a saying question\n"
	.string "that begs your suggestion!\p"
	.string "If I win a match, what can I say\n"
	.string "in a real cool way?$"

gText_ApprenticeWinSpeechThanks11::
	.string "{STR_VAR_1}\p"
	.string "Perfect! That's what I'll use.\n"
	.string "I was right to make you choose!\p"
	.string "And now, I think it'd be best,\n"
	.string "if I were to fly the nest!\p"
	.string "Thanks for all you taught me.\n"
	.string "I'll be off on a battle spree!\p"
	.string "B-O-N-V-O-Y-A-G-E!\n"
	.string "And that spells bon voyage,\l"
	.string "to you this is my homage!$"

gText_ApprenticePickWinSpeech12::
	.string "Oh, yeah, {PLAYER}!\n"
	.string "I found you again today!\p"
	.string "What should I do? Ask you again?\n"
	.string "Why not? I'm already asking you!\p"
	.string "Anyways, {PLAYER}…\n"
	.string "Are you receiving me?\l"
	.string "You are receiving me!\l"
	.string "I need some more advice for me!\p"
	.string "It's about what I should yell.\n"
	.string "Something cool to holler when\l"
	.string "a battle ends well.\p"
	.string "Come on, I wanna hear you say it!$"

gText_ApprenticeWinSpeechThanks12::
	.string "{STR_VAR_1}\p"
	.string "All right, all right!\n"
	.string "I'll use that because it's so tight!\p"
	.string "I'm out of things to ask you.\n"
	.string "Waving bye is all that's left to do.\p"
	.string "But maybe one day we'll meet, with one\n"
	.string "destined to go down in defeat.\p"
	.string "But, it really is time to say farewell.\p"
	.string "Well, {PLAYER}, I have to roam free,\n"
	.string "but don't you forget about me!\p"
	.string "Take care, {PLAYER}!\n"
	.string "Love ya!$"

gText_ApprenticePickWinSpeech13::
	.string "{PLAYER}{KUN}, I'm finished…\n"
	.string "My nose won't stop dripping…\p"
	.string "I was trying to think up something\n"
	.string "cool to say when I win a battle.\p"
	.string "It inspired me so much, it made me cry,\n"
	.string "and now my nose won't stop running…\p"
	.string "So, things being this way,\n"
	.string "I need you to decide for me, {PLAYER}{KUN}.\p"
	.string "When I win a battle,\n"
	.string "what should I say?$"

gText_ApprenticeWinSpeechThanks13::
	.string "{STR_VAR_1}\p"
	.string "… … …That's good.\n"
	.string "No, it's awe inspiring!\l"
	.string "It's bringing fresh tears to my eyes!\p"
	.string "But in spite of my tears and runny\n"
	.string "nose, I will use that saying!\p"
	.string "I'm plumb out of things to ask you,\n"
	.string "{PLAYER}{KUN}.\p"
	.string "From now on, we're rivals!\n"
	.string "Thanks for everything!$"

gText_ApprenticePickWinSpeech14::
	.string "Er… Um…\n"
	.string "{PLAYER}{KUN}…\p"
	.string "Please, don't look at me that way.\n"
	.string "You're making me all nervous.\p"
	.string "I… I need your advice again.\n"
	.string "I'll make it my last, though…\p"
	.string "It's really embarrassing to ask,\n"
	.string "but what if I win a battle?\l"
	.string "What should I say?$"

gText_ApprenticeWinSpeechThanks14::
	.string "{STR_VAR_1}\p"
	.string "Oh… Okay!\n"
	.string "I'll try to say that!\l"
	.string "I might be too nervous to say it…\p"
	.string "Thank you, {PLAYER}{KUN}.\n"
	.string "I have to say good-bye now.\p"
	.string "I'll obey all that you've taught me,\n"
	.string "{PLAYER}{KUN}, and do the best I can.$"

gText_ApprenticePickWinSpeech15::
	.string "Hm? You appear to be {PLAYER}{KUN}…\n"
	.string "But are you really?\l"
	.string "Perhaps a clever {PLAYER} DOLL?\p"
	.string "Oh, no, no, no, don't worry!\n"
	.string "If you really are real, please\l"
	.string "forget about my rudeness.\p"
	.string "No need to be so angry. All I wish for\n"
	.string "is more of your fine advice.\p"
	.string "It concerns a saying.\p"
	.string "More precisely, what should I say\n"
	.string "if I win a battle?$"

gText_ApprenticeWinSpeechThanks15::
	.string "{STR_VAR_1}\p"
	.string "… … … … … …\n"
	.string "When I win a match…\p"
	.string "{STR_VAR_1}\p"
	.string "…Are you serious?\p"
	.string "I see. If you are serious, that's fine.\n"
	.string "I thank you for your time.\p"
	.string "I do hope even I will be able to\n"
	.string "put that saying to good use.\p"
	.string "I seem to have run dry on what advice\n"
	.string "I need.\p"
	.string "I do believe it's high time I bid you\n"
	.string "farewell and strike out on my own.\p"
	.string "Thank you, my mentor!\n"
	.string "I apologize for my skepticism!$"
