CableClub_Text_WelcomeWhichCableClubService:
	.string "Hola.\n"
	.string "Éste es el CLUB del CABLE POKéMON.\p"
	.string "¿Qué te apetece hacer?$"

CableClub_Text_WhichService:
	.string "¿Qué podemos hacer por ti?$"

CableClub_Text_TradeUsingLinkCable::
	.string "Intercambiar PKMN con otro jugador\n"
	.string "usando el cable Game Link de GBA.$"

CableClub_Text_BattleUsingLinkCable::
	.string "Usando el cable Game Link de GBA,\n"
	.string "podrás luchar contra alguien.$"

CableClub_Text_RecordCornerUsingLinkCable::
	.string "Usa un cable Game Link de GBA para\n"
	.string "jugar en el CENTRO de RÉCORDS.$"

@ Unused
CableClub_Text_CloseThisMenu:
	.string "Close this menu.$"

CableClub_Text_NeedTwoMonsForDoubleBattle:
	.string "Para un COMBATE DOBLE, necesitas\n"
	.string "tener al menos dos POKéMON.$"

CableClub_Text_NeedTwoMonsToTrade:
	.string "Para intercambiar POKéMON,\n"
	.string "necesitas tener al menos dos.$"

CableClub_Text_CantTradeEnigmaBerry:
	.string "No puedes intercambiar el POKéMON\n"
	.string "que tiene la BAYA {STR_VAR_1}.$"

gText_PleaseWaitForLink::
	.string "Espera unos instantes.\n"
	.string "Pulsa el Botón B para cancelar.$"

gText_ConfirmLinkWhenPlayersReady::
	.string "Cuando todos estén listos…\n"
	.string "Botón A: confirmar   Botón B: cancelar$"

gText_ConfirmStartLinkWithXPlayers::
	.string "Comenzar conexión con {STR_VAR_1} jugadores…\n"
	.string "Botón A: confirmar   Botón B: cancelar$"

gText_AwaitingLinkup::
	.string "Esperando conexión…\n"
	.string "(…) Botón B: cancelar$"

@ Unused
CableClub_Text_OkayToSaveProgress::
	.string "Your progress must be saved before\n"
	.string "linking. Is it okay to save?$"

CableClub_Text_PleaseEnter:
	.string "Adelante.$"

CableClub_Text_DirectYouToYourRoom:
	.string "Te voy a llevar a tu sala.$"

Text_SomeoneIsNotReadyToLink:
	.string "Uno de los jugadores no está listo\n"
	.string "para realizar la conexión.\p"
	.string "Vuelve cuando todos estéis listos.$"

Text_LinkErrorPleaseReset:
	.string "Error de conexión…\n"
	.string "Comprueba el cable Game Link, reinicia\l"
	.string "la consola e inténtalo de nuevo.$"

Text_PlayersMadeDifferentSelections:
	.string "Los demás jugadores parecen haber\n"
	.string "seleccionado opciones diferentes.$"

CableClub_Text_PleaseVisitAgain:
	.string "Vuelve cuando quieras.$"

CableClub_Text_IncorrectNumberOfParticipants:
	.string "El número de jugadores no es correcto.$"

CableClub_Text_CantSingleBattleWithXPlayers:
	.string "No se puede jugar al modo de combate\n"
	.string "INDIVIDUAL con {STR_VAR_1} jugadores.$"

CableClub_Text_CantDoubleBattleWithXPlayers:
	.string "No se puede jugar al modo de combate\n"
	.string "DOBLE con {STR_VAR_1} jugadores.$"

CableClub_Text_NeedFourPlayers:
	.string "Se necesitan cuatro jugadores\n"
	.string "para jugar a este modo de combate.$"

CableClub_Text_PleaseConfirmNumberAndRestart:
	.string "Confirma el número de jugadores\n"
	.string "y vuelve a empezar.$"

Text_TerminateLinkConfirmation:
	.string "Si sales de la sala, se pondrá fin\n"
	.string "a la conexión. ¿Estás de acuerdo?$"

Text_TerminateLinkPleaseWait:
	.string "Finalizando conexión… Te acompañamos\n"
	.string "fuera de la sala. Espera un momento.$"

CableClub_Text_TooBusyToNotice:
	.string "Este ENTRENADOR no te hace ni caso…$"

CableClub_Text_GotToLookAtTrainerCard:
	.string "¡Bingo! ¡Puedes mirar la FICHA\n"
	.string "de ENTRENADOR de {STR_VAR_1}!$"

CableClub_Text_GotToLookAtColoredTrainerCard:
	.string "¡Bingo! ¡Puedes mirar la FICHA\n"
	.string "de ENTRENADOR de {STR_VAR_1}!\l"
	.string "¡Es de color {STR_VAR_2}!$"

BattleColosseum_2P_Text_TakePlaceStartBattle:
	.string "Puedes comenzar el combate.$"

TradeCenter_Text_TakeSeatStartTrade:
	.string "Puedes comenzar el intercambio.$"

RecordCorner_Text_ThanksForComing:
	.string "Gracias por venir.$"

CableClub_Text_TrainerCardDataOverwritten:
	.string "Se van a sobrescribir los datos\n"
	.string "de la FICHA de ENTRENADOR.$"

CableClub_Text_HopeToSeeYouAgain:
	.string "¡Vuelve cuando quieras!$"

CableClub_Text_NotSetUpForFarAwayRegion:
	.string "Lo siento mucho.\p"
	.string "Aún no podemos realizar intercambios\n"
	.string "con ENTRENADORES de otra región…$"

CableClub_Text_OtherTrainerNotReady:
	.string "El otro ENTRENADOR no está listo.$"

CableClub_Text_YouHaveAMonThatCantBeTaken:
	.string "Tienes al menos un POKéMON\n"
	.string "que no se puede enviar.$"

RecordCorner_Text_TakeSeatAndWait:
	.string "Toma asiento y espera un instante…$"

RecordCorner_Text_PlayerSentOverOneX:
	.string "¡{STR_VAR_1} envió {STR_VAR_2}!$"

CableClub_Text_CantMixWithJapaneseGame:
	.string "Hay un error de conexión.\p"
	.string "No puedes mezclar récords con las\n"
	.string "versiones japonesas de POKéMON\l"
	.string "Rubí y Zafiro.\p"
	.string "Tampoco puedes mezclar a la vez\n"
	.string "récords con la versión japonesa\l"
	.string "de POKéMON Esmeralda y cualquier\l"
	.string "versión de Rubí y Zafiro.$"

CableClub_Text_AdapterNotConnected:
	.string "El Conector inalámbrico de GBA\n"
	.string "no está bien conectado.$"

CableClub_Text_ParticipantsStepUpToCounter:
	.string "Los participantes deben pasar\n"
	.string "por el mostrador de recepción.$"

@ Unused
CableClub_Text_Hello:
	.string "Hello!$"

@ Unused
CableClub_Text_PleaseWait:
	.string "Please wait.$"

CableClub_Text_YouMayTradeHere::
	.string "Aquí puedes intercambiar POKéMON\n"
	.string "con un amigo.$"

CableClub_Text_YouMayBattleHere::
	.string "Aquí puedes luchar contra tus amigos.$"

CableClub_Text_CanMakeBerryPowder::
	.string "Para hacer POLVO de BAYA, hacen\n"
	.string "falta de dos a cinco ENTRENADORES.$"

CableClub_Text_CanMixRecords::
	.string "Se pueden mezclar los récords\n"
	.string "de dos a cuatro jugadores.$"

@ Unused
CableClub_Text_GuideToVariousServices:
	.string "A guide to the WIRELESS CLUB's\n"
	.string "various services.$"

CableClub_Text_CancelSelectedItem::
	.string "Cancelar la selección.$"

@ Unused
CableClub_Text_WhichBattleMode:
	.string "Which battle mode would you like?$"

@ Unused
CableClub_Text_ReturnsToPreviousStep:
	.string "Returns to the previous step.$"

CableClub_Text_NeedBerryForBerryCrush:
	.string "Para usar el MACHACABAYAS,\n"
	.string "necesitas al menos una BAYA.$"

CableClub_Text_NeedTwoMonsForUnionRoom:
	.string "Para entrar en la SALA UNIÓN,\n"
	.string "debes tener al menos dos POKéMON.$"

CableClub_Text_NoEnigmaBerryInUnionRoom:
	.string "Los POKéMON que tienen BAYAS\n"
	.string "{STR_VAR_1} no pueden entrar en la\l"
	.string "SALA UNIÓN.$"

CableClub_Text_UnionRoomAdapterNotConnected:
	.string "Ésta es la SALA UNIÓN del CLUB\n"
	.string "INALÁMBRICO POKéMON.\p"
	.string "Vaya, tu Conector inalámbrico\n"
	.string "de GBA no está bien conectado…\p"
	.string "Vuelve más tarde.$"

@ Unused
CableClub_Text_OhExcuseMe:
	.string "Oh…\n"
	.string "Excuse me!$"

CableClub_Text_PlayerIsWaiting:
	.string "¡Parece que {STR_VAR_1} está jugando\n"
	.string "ahora mismo! ¡Conéctate!$"

MossdeepCity_GameCorner_1F_Text_DescribeWhichGame:
	.string "Si quieres, te explico las reglas.\p"
	.string "¿De qué juego te hablo?$"

MossdeepCity_GameCorner_1F_Text_PokemonJumpInfo:
	.string "“SALTO POKéMON”\p"
	.string "Consigue que a tus POKéMON no los\n"
	.string "atrape la LIANA usando el Botón A.\p"
	.string "Sólo pueden participar los POKéMON\n"
	.string "que midan unos 70 cm o menos.\p"
	.string "A los POKéMON que naden despacio,\n"
	.string "caven o vuelen no se les dará muy\l"
	.string "bien lo de saltar.\p"
	.string "Por ello, estos POKéMON no deben\n"
	.string "participar.\p"
	.string "Si todos saltan a la vez,\n"
	.string "pueden ocurrir cosas estupendas.$"

MossdeepCity_GameCorner_1F_Text_DodrioBerryPickingInfo:
	.string "“DODRIO A POR BAYAS”\p"
	.string "Dile a DODRIO que pille las BAYAS\n"
	.string "que pueda con los tres picos que\l"
	.string "tiene.\p"
	.string "Pulsa derecha, izquierda o arriba\n"
	.string "en el {PLUS} Panel de Control para\l"
	.string "que se mueva.\p"
	.string "Para poder jugar a este juego,\n"
	.string "hay que tener un DODRIO.$"

MossdeepCity_GameCorner_1F_Text_TalkToOldManToPlay:
	.string "If you want to play a game,\n"
	.string "please tell the old man beside me.$"

MossdeepCity_GameCorner_1F_Text_WelcomeCanYouWait:
	.string "Hi, welcome!\n"
	.string "Are you here to play games using\l"
	.string "Wireless Communication?\p"
	.string "Can you wait just a little bit?$"

MossdeepCity_GameCorner_1F_Text_ComeAgain:
	.string "All right, come again!$"

MossdeepCity_GameCorner_1F_Text_AdapterNotConnected:
	.string "The Wireless Adapter isn't connected.\n"
	.string "Come back when it's hooked up!$"

MossdeepCity_GameCorner_1F_Text_PlayWhichGame:
	.string "All right, which game did you want\n"
	.string "to play?$"

MossdeepCity_GameCorner_1F_Text_EnterWhichPokemon:
	.string "Which POKéMON would you like to\n"
	.string "enter?$"

MossdeepCity_GameCorner_1F_Text_AllGoodToGo:
	.string "Okay, you're all good to go.\n"
	.string "Don't let the others beat you!$"

@ Unused
MossdeepCity_GameCorner_1F_Text_LeavingDoComeAgain:
	.string "Are you leaving now?\n"
	.string "Do come again!$"

MossdeepCity_GameCorner_1F_Text_ExplainRequiredMon:
	.string "It doesn't look like you have any\n"
	.string "POKéMON that you can enter…\p"
	.string "Would you like me to explain what\n"
	.string "kinds of POKéMON can enter?$"

MossdeepCity_GameCorner_1F_Text_ShortJumpingPokemonAllowed:
	.string "“POKéMON JUMP” is open to POKéMON\n"
	.string "around 28 inches or less.\p"
	.string "What you can't enter are those\n"
	.string "POKéMON that can't jump.\p"
	.string "You know, like POKéMON that only\n"
	.string "swim, burrow, or fly.\p"
	.string "That's all you need to know.$"

MossdeepCity_GameCorner_1F_Text_OnlyDodrioAllowed:
	.string "DODRIO BERRY-PICKING is a game that \n"
	.string "only DODRIO may enter.$"

@ Unused
MossdeepCity_GameCorner_1F_Text_RetryPlease:
	.string "Could you retry this from the start\n"
	.string "again, please?$"

CableClub_Text_WelcomeWhichDirectCornerRoom:
	.string "Welcome to the POKéMON WIRELESS\n"
	.string "CLUB DIRECT CORNER.\p"
	.string "You may interact directly with\n"
	.string "your friends here.\p"
	.string "Which room would you like to\n"
	.string "enter?$"

CableClub_Text_TradePokemon:
	.string "Would you like to trade POKéMON?$"

CableClub_Text_PlayWhichBattleMode:
	.string "Which Battle Mode would you like\n"
	.string "to play?$"

CableClub_Text_AccessRecordCorner:
	.string "Would you like to access\n"
	.string "the RECORD CORNER?$"

CableClub_Text_UseBerryCrush:
	.string "Would you like to use the\n"
	.string "BERRY CRUSH System?$"

CableClub_Text_ExplainBattleModes:
	.string "There are three Battle Modes.\p"
	.string "SINGLE BATTLE is for two TRAINERS\n"
	.string "with one or more POKéMON each.\p"
	.string "Each TRAINER can have one POKéMON\n"
	.string "in battle at a time.\p"
	.string "DOUBLE BATTLE is for two TRAINERS\n"
	.string "with two or more POKéMON each.\p"
	.string "Each TRAINER will send out two\n"
	.string "POKéMON in battle at a time.\p"
	.string "MULTI BATTLE is for four TRAINERS\n"
	.string "with one or more POKéMON each.\p"
	.string "Each TRAINER can have one POKéMON\n"
	.string "in battle at a time.$"

CableClub_Text_ChooseGroupLeaderOfTwo:
	.string "Please decide which of you two\n"
	.string "will become the LEADER.\p"
	.string "The other player must then choose\n"
	.string "“JOIN GROUP.”$"

CableClub_Text_ChooseGroupLeaderOfFour:
	.string "Please decide which of you four\n"
	.string "will become the GROUP LEADER.\p"
	.string "The other players must then choose\n"
	.string "“JOIN GROUP.”$"

CableClub_Text_ChooseGroupLeader:
	.string "Please decide which of you will\n"
	.string "become the GROUP LEADER.\p"
	.string "The other players must then choose\n"
	.string "“JOIN GROUP.”$"

CableClub_Text_WelcomeUnionRoomEnter:
	.string "Welcome to the POKéMON WIRELESS\n"
	.string "CLUB UNION ROOM.\p"
	.string "You may interact directly with\n"
	.string "other TRAINERS here, some of\l"
	.string "whom you may not even know.\p"
	.string "Would you like to enter the ROOM?$"

CableClub_Text_UnionRoomInfo:
	.string "The TRAINERS in the UNION ROOM\n"
	.string "will be those players around you\l"
	.string "who have also entered the ROOM.\p"
	.string "You may do all sorts of things\n"
	.string "here, such as exchanging greetings.\p"
	.string "You may enter two POKéMON up to\n"
	.string "Lv. 30 for a one-on-one battle.\p"
	.string "You may take part in a chat with\n"
	.string "two to five people.\p"
	.string "Or, you may register a POKéMON for\n"
	.string "trade.\p"
	.string "Would you like to enter the ROOM?$"

CableClub_Text_EnjoyUnionRoom:
	.string "I hope you enjoy your time in\n"
	.string "the UNION ROOM.$"

CableClub_Text_FirstTimeRightThisWay:
	.string "Hello!\n"
	.string "My name is TEALA.\p"
	.string "This must be your first time\n"
	.string "up here.\p"
	.string "I'll show you how the Wireless\n"
	.string "Communication System works.\p"
	.string "First, I need to show you this\n"
	.string "floor of our POKéMON CENTER.\p"
	.string "Right this way, please.$"

CableClub_Text_ExplainWirelessClubFirstTime:
	.string "On the top floor, there are two\n"
	.string "rooms.\p"
	.string "First, the room on the left.\n"
	.string "It's the UNION ROOM.\p"
	.string "You may link up with TRAINERS\n"
	.string "around you who have also entered\l"
	.string "the UNION ROOM.\p"
	.string "With them, you may do things like\n"
	.string "chat, battle, and trade.\p"
	.string "Second, the room on the right is\n"
	.string "the DIRECT CORNER.\p"
	.string "You may trade or battle POKéMON\n"
	.string "with your friends in this room.\p"
	.string "If the Wireless Adapter isn't\n"
	.string "connected, you may still link up\l"
	.string "using a GBA Game Link cable.\p"
	.string "If that is the case, you must go\n"
	.string "to the DIRECT CORNER.\p"
	.string "I hope you enjoy the Wireless \n"
	.string "Communication System.$"

CableClub_Text_AskAboutLinking:
	.string "Hello, {PLAYER}!\p"
	.string "It's me, TEALA, the POKéMON\n"
	.string "CENTER 2F attendant.\p"
	.string "Is there something you needed to\n"
	.string "ask me about linking?$"

CableClub_Text_ExplainWirelessClub:
	.string "Let me explain how the POKéMON\n"
	.string "WIRELESS CLUB works.\p"
	.string "On this, the top floor, there are\n"
	.string "two rooms.\p"
	.string "First, the room on the left.\n"
	.string "It's the UNION ROOM.\p"
	.string "You may link up with TRAINERS\n"
	.string "around you who have also entered\l"
	.string "the UNION ROOM.\p"
	.string "With them, you may do things like\n"
	.string "chat, battle, and trade.\p"
	.string "Second, the room on the right is\n"
	.string "the DIRECT CORNER.\p"
	.string "You may trade or battle POKéMON\n"
	.string "with your friends in this room.\p"
	.string "Sometimes, you may not be able to\n"
	.string "find your friends in the UNION ROOM\l"
	.string "or the DIRECT CORNER.\p"
	.string "In that case, please move closer\n"
	.string "to your friends.\p"
	.string "If the Wireless Adapter isn't\n"
	.string "connected, you may still link up\l"
	.string "using a GBA Game Link cable.\p"
	.string "If that is the case, you must go\n"
	.string "to the DIRECT CORNER.\p"
	.string "I hope you enjoy the Wireless \n"
	.string "Communication System.$"

CableClub_Text_HopeYouEnjoyWirelessSystem:
	.string "I hope you enjoy the Wireless\n"
	.string "Communication System.$"
